from enum import Enum

SYSTEM_CAN_MESSAGE_ID_OFFSET = 4
SYSTEM_CAN_MESSAGE_PRIORITY_BIT = 0x400

class SystemCanDevice(Enum):
  SYSTEM_CAN_DEVICE_BMS_CARRIER = 0
  SYSTEM_CAN_DEVICE_CAN_COMMUNICATION = 1
  SYSTEM_CAN_DEVICE_CENTRE_CONSOLE = 2
  SYSTEM_CAN_DEVICE_TELEMETRY = 3
  NUM_SYSTEM_CAN_DEVICES = 4