#pragma once

/************************************************************************************************
 * @file   can_manager.h
 *
 * @brief  Header file defining the CanManager class
 *
 * @date   2026-03-12
 * @author Midnight Sun Team #24 - MSXVI
 ************************************************************************************************/

/** @warning  This file is autogenerated */

/* Standard library Headers */
#include <cstdint>
#include <string>
#include <vector>

/* Inter-component Headers */
#include <nlohmann/json.hpp>

/* Intra-component Headers */

/**
 * @defgroup CanManager
 * @brief    CAN Manager orchestration class
 * @{
 */

/**
 * @struct  CanFlagInfo
 * @brief   Metadata for single flag within bitfield signal
 */
struct CanFlagInfo {
  std::string name;    /**< Flag name */
  unsigned int length; /**< Flag length in bits */
  unsigned int offset; /**< Flag bit offset within the bitfield */
};

/**
 * @struct  CanSignalInfo
 * @brief   Metadata for single CAN signal
 */
struct CanSignalInfo {
  std::string name;               /**< Signal name */
  unsigned int length;            /**< Signal length in bits */
  unsigned int start_bit;         /**< Signal start bit position */
  std::string type;               /**< Signal type ("standard" or "bitfield") */
  std::vector<CanFlagInfo> flags; /**< Flags within a bitfield signal (empty for standard) */
};

/**
 * @struct  CanMessageInfo
 * @brief   Metadata for single CAN message
 */
struct CanMessageInfo {
  std::string name;                   /**< Message name (lowercase) */
  std::string sender;                 /**< Board that sends this message */
  unsigned int id;                    /**< CAN message ID */
  unsigned int dlc;                   /**< Data length code in bytes */
  unsigned int cycle_speed;           /**< Cycle speed (ms) */
  std::string cycle;                  /**< Cycle group (fast/medium/slow) */
  bool critical;                      /**< Whether message is critical */
  std::vector<CanSignalInfo> signals; /**< List of signals in this message */
};

/**
 * @class   CanManager
 * @brief   layer providing human readable access to CAN signals
 * @details Wraps the setters (CanScheduler) and getters (JSON cache)
 *          with methods autogenerated from YAML config.
 */
class CanManager {
 private:
  static const constexpr char *CAN_JSON_PROJECT = "CANListener";   /**< JSON project name for CAN data */
  static const constexpr char *CAN_JSON_MESSAGES_KEY = "messages"; /**< JSON key for CAN messages */

  bool m_isRunning; /**< Whether sim is active */

 public:
  /**
   * @brief   Constructs CanManager object
   */
  CanManager();

  /**
   * @brief   Start CAN simulation with scheduler and listener
   */
  void startSimulation();

  /**
   * @brief   Stop simulation
   */
  void stopSimulation();

  /**
   * @brief   Check if the CAN simulation is running
   * @return  true if running, false otherwise
   */
  bool isRunning() const;

  /* Message Metadata */

  /**
   * @brief   Get metadata for all CAN messages
   * @return  Vector of CanMessageInfo structs
   */
  std::vector<CanMessageInfo> getMessageInfoList() const;

  /**
   * @brief   Get metadata for a specific CAN message by name
   * @param   message_name Name of the CAN message
   * @return  CanMessageInfo struct (empty name if not found)
   */
  CanMessageInfo getMessageInfo(const std::string &message_name) const;

  /* Bulk Accessors */

  /**
   * @brief   Get all CAN signal data as a JSON object
   * @return  JSON object with all messages and signals
   */
  nlohmann::json getAllSignals() const;

  /**
   * @brief   Get all signals for fast_one_shot_msg as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_fast_one_shot_msg() const;

  /**
   * @brief   Get all signals for medium_one_shot_msg as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_medium_one_shot_msg() const;

  /**
   * @brief   Get all signals for slow_one_shot_msg as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_slow_one_shot_msg() const;

  /**
   * @brief   Get all signals for pedal as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_pedal() const;

  /**
   * @brief   Get all signals for motor_velocity as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_motor_velocity() const;

  /**
   * @brief   Get all signals for motor_temperature as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_motor_temperature() const;

  /**
   * @brief   Get all signals for fc_power_group_a as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_fc_power_group_a() const;

  /**
   * @brief   Get all signals for fc_power_group_b as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_fc_power_group_b() const;

  /**
   * @brief   Get all signals for fc_power_lights_group as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_fc_power_lights_group() const;

  /**
   * @brief   Get all signals for gyro_data as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_gyro_data() const;

  /**
   * @brief   Get all signals for accel_data as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_accel_data() const;

  /**
   * @brief   Get all signals for rear_controller_status as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_rear_controller_status() const;

  /**
   * @brief   Get all signals for battery_stats_a as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_battery_stats_a() const;

  /**
   * @brief   Get all signals for battery_stats_b as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_battery_stats_b() const;

  /**
   * @brief   Get all signals for power_input_stats as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_power_input_stats() const;

  /**
   * @brief   Get all signals for afe1_status_a as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_afe1_status_a() const;

  /**
   * @brief   Get all signals for afe1_status_b as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_afe1_status_b() const;

  /**
   * @brief   Get all signals for afe2_status_a as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_afe2_status_a() const;

  /**
   * @brief   Get all signals for afe2_status_b as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_afe2_status_b() const;

  /**
   * @brief   Get all signals for afe_temperature as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_afe_temperature() const;

  /**
   * @brief   Get all signals for steering as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_steering() const;

  /**
   * @brief   Get all signals for telemetry as JSON
   * @return  JSON object with signal values
   */
  nlohmann::json get_telemetry() const;

  /* Per Signal Getters */

  /**
   * @brief   Get fast_one_shot_msg.sig1 (raw value)
   * @return  Current signal value
   */
  uint16_t get_fast_one_shot_msg_sig1() const;

  /**
   * @brief   Get fast_one_shot_msg.sig2 (raw value)
   * @return  Current signal value
   */
  uint16_t get_fast_one_shot_msg_sig2() const;

  /**
   * @brief   Get medium_one_shot_msg.sig1 (raw value)
   * @return  Current signal value
   */
  uint16_t get_medium_one_shot_msg_sig1() const;

  /**
   * @brief   Get medium_one_shot_msg.sig2 (raw value)
   * @return  Current signal value
   */
  uint16_t get_medium_one_shot_msg_sig2() const;

  /**
   * @brief   Get slow_one_shot_msg.sig1 (raw value)
   * @return  Current signal value
   */
  uint16_t get_slow_one_shot_msg_sig1() const;

  /**
   * @brief   Get slow_one_shot_msg.sig2 (raw value)
   * @return  Current signal value
   */
  uint16_t get_slow_one_shot_msg_sig2() const;

  /**
   * @brief   Get pedal.percentage (raw value)
   * @return  Current signal value
   */
  uint32_t get_pedal_percentage() const;

  /**
   * @brief   Get pedal.data (raw value)
   * @return  Current signal value
   */
  uint8_t get_pedal_data() const;

  /**
   * @brief   Get pedal.data.drive_state flag
   * @return  Current flag value
   */
  uint8_t get_pedal_data_drive_state() const;

  /**
   * @brief   Get pedal.data.brake_enabled flag
   * @return  Current flag value
   */
  uint8_t get_pedal_data_brake_enabled() const;

  /**
   * @brief   Get pedal.data.regen_enabled flag
   * @return  Current flag value
   */
  uint8_t get_pedal_data_regen_enabled() const;

  /**
   * @brief   Get motor_velocity.vehicle_velocity (raw value)
   * @return  Current signal value
   */
  uint32_t get_motor_velocity_vehicle_velocity() const;

  /**
   * @brief   Get motor_velocity.motor_velocity (raw value)
   * @return  Current signal value
   */
  uint32_t get_motor_velocity_motor_velocity() const;

  /**
   * @brief   Get motor_temperature.heat_sink_temp (raw value)
   * @return  Current signal value
   */
  uint32_t get_motor_temperature_heat_sink_temp() const;

  /**
   * @brief   Get motor_temperature.motor_temp (raw value)
   * @return  Current signal value
   */
  uint32_t get_motor_temperature_motor_temp() const;

  /**
   * @brief   Get fc_power_group_a.rev_cam_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_group_a_rev_cam_current() const;

  /**
   * @brief   Get fc_power_group_a.telem_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_group_a_telem_current() const;

  /**
   * @brief   Get fc_power_group_a.steering_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_group_a_steering_current() const;

  /**
   * @brief   Get fc_power_group_a.driver_fan_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_group_a_driver_fan_current() const;

  /**
   * @brief   Get fc_power_group_b.horn_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_group_b_horn_current() const;

  /**
   * @brief   Get fc_power_group_b.spare_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_group_b_spare_current() const;

  /**
   * @brief   Get fc_power_lights_group.brake_light_sig_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_lights_group_brake_light_sig_current() const;

  /**
   * @brief   Get fc_power_lights_group.bps_light_sig_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_lights_group_bps_light_sig_current() const;

  /**
   * @brief   Get fc_power_lights_group.right_sig_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_lights_group_right_sig_current() const;

  /**
   * @brief   Get fc_power_lights_group.left_sig_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_fc_power_lights_group_left_sig_current() const;

  /**
   * @brief   Get gyro_data.x_axis (raw value)
   * @return  Current signal value
   */
  uint16_t get_gyro_data_x_axis() const;

  /**
   * @brief   Get gyro_data.y_axis (raw value)
   * @return  Current signal value
   */
  uint16_t get_gyro_data_y_axis() const;

  /**
   * @brief   Get gyro_data.z_axis (raw value)
   * @return  Current signal value
   */
  uint16_t get_gyro_data_z_axis() const;

  /**
   * @brief   Get accel_data.x_axis (raw value)
   * @return  Current signal value
   */
  uint16_t get_accel_data_x_axis() const;

  /**
   * @brief   Get accel_data.y_axis (raw value)
   * @return  Current signal value
   */
  uint16_t get_accel_data_y_axis() const;

  /**
   * @brief   Get accel_data.z_axis (raw value)
   * @return  Current signal value
   */
  uint16_t get_accel_data_z_axis() const;

  /**
   * @brief   Get rear_controller_status.triggers (raw value)
   * @return  Current signal value
   */
  uint16_t get_rear_controller_status_triggers() const;

  /**
   * @brief   Get rear_controller_status.triggers.bps_fault flag
   * @return  Current flag value
   */
  uint16_t get_rear_controller_status_triggers_bps_fault() const;

  /**
   * @brief   Get rear_controller_status.triggers.relay_state flag
   * @return  Current flag value
   */
  uint16_t get_rear_controller_status_triggers_relay_state() const;

  /**
   * @brief   Get rear_controller_status.triggers.power_state flag
   * @return  Current flag value
   */
  uint16_t get_rear_controller_status_triggers_power_state() const;

  /**
   * @brief   Get rear_controller_status.triggers.afe_status flag
   * @return  Current flag value
   */
  uint16_t get_rear_controller_status_triggers_afe_status() const;

  /**
   * @brief   Get rear_controller_status.triggers.motor_precharge_complete flag
   * @return  Current flag value
   */
  uint16_t get_rear_controller_status_triggers_motor_precharge_complete() const;

  /**
   * @brief   Get battery_stats_a.pack_voltage (raw value)
   * @return  Current signal value
   */
  uint16_t get_battery_stats_a_pack_voltage() const;

  /**
   * @brief   Get battery_stats_a.pack_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_battery_stats_a_pack_current() const;

  /**
   * @brief   Get battery_stats_a.pack_soc (raw value)
   * @return  Current signal value
   */
  uint16_t get_battery_stats_a_pack_soc() const;

  /**
   * @brief   Get battery_stats_b.max_cell_voltage (raw value)
   * @return  Current signal value
   */
  uint16_t get_battery_stats_b_max_cell_voltage() const;

  /**
   * @brief   Get battery_stats_b.min_cell_voltage (raw value)
   * @return  Current signal value
   */
  uint16_t get_battery_stats_b_min_cell_voltage() const;

  /**
   * @brief   Get battery_stats_b.max_temperature (raw value)
   * @return  Current signal value
   */
  uint16_t get_battery_stats_b_max_temperature() const;

  /**
   * @brief   Get power_input_stats.input_dcdc_voltage (raw value)
   * @return  Current signal value
   */
  uint16_t get_power_input_stats_input_dcdc_voltage() const;

  /**
   * @brief   Get power_input_stats.input_dcdc_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_power_input_stats_input_dcdc_current() const;

  /**
   * @brief   Get power_input_stats.input_aux_voltage (raw value)
   * @return  Current signal value
   */
  uint16_t get_power_input_stats_input_aux_voltage() const;

  /**
   * @brief   Get power_input_stats.input_aux_current (raw value)
   * @return  Current signal value
   */
  uint16_t get_power_input_stats_input_aux_current() const;

  /**
   * @brief   Get afe1_status_a.id (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe1_status_a_id() const;

  /**
   * @brief   Get afe1_status_a.voltage_0 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe1_status_a_voltage_0() const;

  /**
   * @brief   Get afe1_status_a.voltage_1 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe1_status_a_voltage_1() const;

  /**
   * @brief   Get afe1_status_a.voltage_2 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe1_status_a_voltage_2() const;

  /**
   * @brief   Get afe1_status_b.id (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe1_status_b_id() const;

  /**
   * @brief   Get afe1_status_b.voltage_0 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe1_status_b_voltage_0() const;

  /**
   * @brief   Get afe1_status_b.voltage_1 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe1_status_b_voltage_1() const;

  /**
   * @brief   Get afe1_status_b.voltage_2 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe1_status_b_voltage_2() const;

  /**
   * @brief   Get afe2_status_a.id (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe2_status_a_id() const;

  /**
   * @brief   Get afe2_status_a.voltage_0 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe2_status_a_voltage_0() const;

  /**
   * @brief   Get afe2_status_a.voltage_1 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe2_status_a_voltage_1() const;

  /**
   * @brief   Get afe2_status_a.voltage_2 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe2_status_a_voltage_2() const;

  /**
   * @brief   Get afe2_status_b.id (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe2_status_b_id() const;

  /**
   * @brief   Get afe2_status_b.voltage_0 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe2_status_b_voltage_0() const;

  /**
   * @brief   Get afe2_status_b.voltage_1 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe2_status_b_voltage_1() const;

  /**
   * @brief   Get afe2_status_b.voltage_2 (raw value)
   * @return  Current signal value
   */
  uint16_t get_afe2_status_b_voltage_2() const;

  /**
   * @brief   Get afe_temperature.id (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe_temperature_id() const;

  /**
   * @brief   Get afe_temperature.temperature_0 (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe_temperature_temperature_0() const;

  /**
   * @brief   Get afe_temperature.temperature_1 (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe_temperature_temperature_1() const;

  /**
   * @brief   Get afe_temperature.temperature_2 (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe_temperature_temperature_2() const;

  /**
   * @brief   Get afe_temperature.temperature_3 (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe_temperature_temperature_3() const;

  /**
   * @brief   Get afe_temperature.temperature_4 (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe_temperature_temperature_4() const;

  /**
   * @brief   Get afe_temperature.temperature_5 (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe_temperature_temperature_5() const;

  /**
   * @brief   Get afe_temperature.temperature_6 (raw value)
   * @return  Current signal value
   */
  uint8_t get_afe_temperature_temperature_6() const;

  /**
   * @brief   Get steering.cruise_control_target_velocity (raw value)
   * @return  Current signal value
   */
  uint32_t get_steering_cruise_control_target_velocity() const;

  /**
   * @brief   Get steering.buttons (raw value)
   * @return  Current signal value
   */
  uint8_t get_steering_buttons() const;

  /**
   * @brief   Get steering.buttons.drive_state flag
   * @return  Current flag value
   */
  uint8_t get_steering_buttons_drive_state() const;

  /**
   * @brief   Get steering.buttons.lights flag
   * @return  Current flag value
   */
  uint8_t get_steering_buttons_lights() const;

  /**
   * @brief   Get steering.buttons.cruise_control_enabled flag
   * @return  Current flag value
   */
  uint8_t get_steering_buttons_cruise_control_enabled() const;

  /**
   * @brief   Get steering.buttons.hazard_enabled flag
   * @return  Current flag value
   */
  uint8_t get_steering_buttons_hazard_enabled() const;

  /**
   * @brief   Get steering.buttons.horn_enabled flag
   * @return  Current flag value
   */
  uint8_t get_steering_buttons_horn_enabled() const;

  /**
   * @brief   Get steering.buttons.regen_enabled flag
   * @return  Current flag value
   */
  uint8_t get_steering_buttons_regen_enabled() const;

  /**
   * @brief   Get telemetry.telemetry_data (raw value)
   * @return  Current signal value
   */
  uint64_t get_telemetry_telemetry_data() const;

  /* Per Signal Setters */

  /**
   * @brief   Set fast_one_shot_msg.sig1 (raw value)
   * @param   value New value for the signal
   */
  void set_fast_one_shot_msg_sig1(uint16_t value);

  /**
   * @brief   Set fast_one_shot_msg.sig2 (raw value)
   * @param   value New value for the signal
   */
  void set_fast_one_shot_msg_sig2(uint16_t value);

  /**
   * @brief   Set medium_one_shot_msg.sig1 (raw value)
   * @param   value New value for the signal
   */
  void set_medium_one_shot_msg_sig1(uint16_t value);

  /**
   * @brief   Set medium_one_shot_msg.sig2 (raw value)
   * @param   value New value for the signal
   */
  void set_medium_one_shot_msg_sig2(uint16_t value);

  /**
   * @brief   Set slow_one_shot_msg.sig1 (raw value)
   * @param   value New value for the signal
   */
  void set_slow_one_shot_msg_sig1(uint16_t value);

  /**
   * @brief   Set slow_one_shot_msg.sig2 (raw value)
   * @param   value New value for the signal
   */
  void set_slow_one_shot_msg_sig2(uint16_t value);

  /**
   * @brief   Set pedal.percentage (raw value)
   * @param   value New value for the signal
   */
  void set_pedal_percentage(uint32_t value);

  /**
   * @brief   Set pedal.data (raw value)
   * @param   value New value for the signal
   */
  void set_pedal_data(uint8_t value);

  /**
   * @brief   Set pedal.data.drive_state flag
   * @param   value New value for the flag
   */
  void set_pedal_data_drive_state(uint8_t value);

  /**
   * @brief   Set pedal.data.brake_enabled flag
   * @param   value New value for the flag
   */
  void set_pedal_data_brake_enabled(uint8_t value);

  /**
   * @brief   Set pedal.data.regen_enabled flag
   * @param   value New value for the flag
   */
  void set_pedal_data_regen_enabled(uint8_t value);

  /**
   * @brief   Set motor_velocity.vehicle_velocity (raw value)
   * @param   value New value for the signal
   */
  void set_motor_velocity_vehicle_velocity(uint32_t value);

  /**
   * @brief   Set motor_velocity.motor_velocity (raw value)
   * @param   value New value for the signal
   */
  void set_motor_velocity_motor_velocity(uint32_t value);

  /**
   * @brief   Set motor_temperature.heat_sink_temp (raw value)
   * @param   value New value for the signal
   */
  void set_motor_temperature_heat_sink_temp(uint32_t value);

  /**
   * @brief   Set motor_temperature.motor_temp (raw value)
   * @param   value New value for the signal
   */
  void set_motor_temperature_motor_temp(uint32_t value);

  /**
   * @brief   Set fc_power_group_a.rev_cam_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_group_a_rev_cam_current(uint16_t value);

  /**
   * @brief   Set fc_power_group_a.telem_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_group_a_telem_current(uint16_t value);

  /**
   * @brief   Set fc_power_group_a.steering_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_group_a_steering_current(uint16_t value);

  /**
   * @brief   Set fc_power_group_a.driver_fan_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_group_a_driver_fan_current(uint16_t value);

  /**
   * @brief   Set fc_power_group_b.horn_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_group_b_horn_current(uint16_t value);

  /**
   * @brief   Set fc_power_group_b.spare_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_group_b_spare_current(uint16_t value);

  /**
   * @brief   Set fc_power_lights_group.brake_light_sig_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_lights_group_brake_light_sig_current(uint16_t value);

  /**
   * @brief   Set fc_power_lights_group.bps_light_sig_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_lights_group_bps_light_sig_current(uint16_t value);

  /**
   * @brief   Set fc_power_lights_group.right_sig_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_lights_group_right_sig_current(uint16_t value);

  /**
   * @brief   Set fc_power_lights_group.left_sig_current (raw value)
   * @param   value New value for the signal
   */
  void set_fc_power_lights_group_left_sig_current(uint16_t value);

  /**
   * @brief   Set gyro_data.x_axis (raw value)
   * @param   value New value for the signal
   */
  void set_gyro_data_x_axis(uint16_t value);

  /**
   * @brief   Set gyro_data.y_axis (raw value)
   * @param   value New value for the signal
   */
  void set_gyro_data_y_axis(uint16_t value);

  /**
   * @brief   Set gyro_data.z_axis (raw value)
   * @param   value New value for the signal
   */
  void set_gyro_data_z_axis(uint16_t value);

  /**
   * @brief   Set accel_data.x_axis (raw value)
   * @param   value New value for the signal
   */
  void set_accel_data_x_axis(uint16_t value);

  /**
   * @brief   Set accel_data.y_axis (raw value)
   * @param   value New value for the signal
   */
  void set_accel_data_y_axis(uint16_t value);

  /**
   * @brief   Set accel_data.z_axis (raw value)
   * @param   value New value for the signal
   */
  void set_accel_data_z_axis(uint16_t value);

  /**
   * @brief   Set rear_controller_status.triggers (raw value)
   * @param   value New value for the signal
   */
  void set_rear_controller_status_triggers(uint16_t value);

  /**
   * @brief   Set rear_controller_status.triggers.bps_fault flag
   * @param   value New value for the flag
   */
  void set_rear_controller_status_triggers_bps_fault(uint16_t value);

  /**
   * @brief   Set rear_controller_status.triggers.relay_state flag
   * @param   value New value for the flag
   */
  void set_rear_controller_status_triggers_relay_state(uint16_t value);

  /**
   * @brief   Set rear_controller_status.triggers.power_state flag
   * @param   value New value for the flag
   */
  void set_rear_controller_status_triggers_power_state(uint16_t value);

  /**
   * @brief   Set rear_controller_status.triggers.afe_status flag
   * @param   value New value for the flag
   */
  void set_rear_controller_status_triggers_afe_status(uint16_t value);

  /**
   * @brief   Set rear_controller_status.triggers.motor_precharge_complete flag
   * @param   value New value for the flag
   */
  void set_rear_controller_status_triggers_motor_precharge_complete(uint16_t value);

  /**
   * @brief   Set battery_stats_a.pack_voltage (raw value)
   * @param   value New value for the signal
   */
  void set_battery_stats_a_pack_voltage(uint16_t value);

  /**
   * @brief   Set battery_stats_a.pack_current (raw value)
   * @param   value New value for the signal
   */
  void set_battery_stats_a_pack_current(uint16_t value);

  /**
   * @brief   Set battery_stats_a.pack_soc (raw value)
   * @param   value New value for the signal
   */
  void set_battery_stats_a_pack_soc(uint16_t value);

  /**
   * @brief   Set battery_stats_b.max_cell_voltage (raw value)
   * @param   value New value for the signal
   */
  void set_battery_stats_b_max_cell_voltage(uint16_t value);

  /**
   * @brief   Set battery_stats_b.min_cell_voltage (raw value)
   * @param   value New value for the signal
   */
  void set_battery_stats_b_min_cell_voltage(uint16_t value);

  /**
   * @brief   Set battery_stats_b.max_temperature (raw value)
   * @param   value New value for the signal
   */
  void set_battery_stats_b_max_temperature(uint16_t value);

  /**
   * @brief   Set power_input_stats.input_dcdc_voltage (raw value)
   * @param   value New value for the signal
   */
  void set_power_input_stats_input_dcdc_voltage(uint16_t value);

  /**
   * @brief   Set power_input_stats.input_dcdc_current (raw value)
   * @param   value New value for the signal
   */
  void set_power_input_stats_input_dcdc_current(uint16_t value);

  /**
   * @brief   Set power_input_stats.input_aux_voltage (raw value)
   * @param   value New value for the signal
   */
  void set_power_input_stats_input_aux_voltage(uint16_t value);

  /**
   * @brief   Set power_input_stats.input_aux_current (raw value)
   * @param   value New value for the signal
   */
  void set_power_input_stats_input_aux_current(uint16_t value);

  /**
   * @brief   Set afe1_status_a.id (raw value)
   * @param   value New value for the signal
   */
  void set_afe1_status_a_id(uint8_t value);

  /**
   * @brief   Set afe1_status_a.voltage_0 (raw value)
   * @param   value New value for the signal
   */
  void set_afe1_status_a_voltage_0(uint16_t value);

  /**
   * @brief   Set afe1_status_a.voltage_1 (raw value)
   * @param   value New value for the signal
   */
  void set_afe1_status_a_voltage_1(uint16_t value);

  /**
   * @brief   Set afe1_status_a.voltage_2 (raw value)
   * @param   value New value for the signal
   */
  void set_afe1_status_a_voltage_2(uint16_t value);

  /**
   * @brief   Set afe1_status_b.id (raw value)
   * @param   value New value for the signal
   */
  void set_afe1_status_b_id(uint8_t value);

  /**
   * @brief   Set afe1_status_b.voltage_0 (raw value)
   * @param   value New value for the signal
   */
  void set_afe1_status_b_voltage_0(uint16_t value);

  /**
   * @brief   Set afe1_status_b.voltage_1 (raw value)
   * @param   value New value for the signal
   */
  void set_afe1_status_b_voltage_1(uint16_t value);

  /**
   * @brief   Set afe1_status_b.voltage_2 (raw value)
   * @param   value New value for the signal
   */
  void set_afe1_status_b_voltage_2(uint16_t value);

  /**
   * @brief   Set afe2_status_a.id (raw value)
   * @param   value New value for the signal
   */
  void set_afe2_status_a_id(uint8_t value);

  /**
   * @brief   Set afe2_status_a.voltage_0 (raw value)
   * @param   value New value for the signal
   */
  void set_afe2_status_a_voltage_0(uint16_t value);

  /**
   * @brief   Set afe2_status_a.voltage_1 (raw value)
   * @param   value New value for the signal
   */
  void set_afe2_status_a_voltage_1(uint16_t value);

  /**
   * @brief   Set afe2_status_a.voltage_2 (raw value)
   * @param   value New value for the signal
   */
  void set_afe2_status_a_voltage_2(uint16_t value);

  /**
   * @brief   Set afe2_status_b.id (raw value)
   * @param   value New value for the signal
   */
  void set_afe2_status_b_id(uint8_t value);

  /**
   * @brief   Set afe2_status_b.voltage_0 (raw value)
   * @param   value New value for the signal
   */
  void set_afe2_status_b_voltage_0(uint16_t value);

  /**
   * @brief   Set afe2_status_b.voltage_1 (raw value)
   * @param   value New value for the signal
   */
  void set_afe2_status_b_voltage_1(uint16_t value);

  /**
   * @brief   Set afe2_status_b.voltage_2 (raw value)
   * @param   value New value for the signal
   */
  void set_afe2_status_b_voltage_2(uint16_t value);

  /**
   * @brief   Set afe_temperature.id (raw value)
   * @param   value New value for the signal
   */
  void set_afe_temperature_id(uint8_t value);

  /**
   * @brief   Set afe_temperature.temperature_0 (raw value)
   * @param   value New value for the signal
   */
  void set_afe_temperature_temperature_0(uint8_t value);

  /**
   * @brief   Set afe_temperature.temperature_1 (raw value)
   * @param   value New value for the signal
   */
  void set_afe_temperature_temperature_1(uint8_t value);

  /**
   * @brief   Set afe_temperature.temperature_2 (raw value)
   * @param   value New value for the signal
   */
  void set_afe_temperature_temperature_2(uint8_t value);

  /**
   * @brief   Set afe_temperature.temperature_3 (raw value)
   * @param   value New value for the signal
   */
  void set_afe_temperature_temperature_3(uint8_t value);

  /**
   * @brief   Set afe_temperature.temperature_4 (raw value)
   * @param   value New value for the signal
   */
  void set_afe_temperature_temperature_4(uint8_t value);

  /**
   * @brief   Set afe_temperature.temperature_5 (raw value)
   * @param   value New value for the signal
   */
  void set_afe_temperature_temperature_5(uint8_t value);

  /**
   * @brief   Set afe_temperature.temperature_6 (raw value)
   * @param   value New value for the signal
   */
  void set_afe_temperature_temperature_6(uint8_t value);

  /**
   * @brief   Set steering.cruise_control_target_velocity (raw value)
   * @param   value New value for the signal
   */
  void set_steering_cruise_control_target_velocity(uint32_t value);

  /**
   * @brief   Set steering.buttons (raw value)
   * @param   value New value for the signal
   */
  void set_steering_buttons(uint8_t value);

  /**
   * @brief   Set steering.buttons.drive_state flag
   * @param   value New value for the flag
   */
  void set_steering_buttons_drive_state(uint8_t value);

  /**
   * @brief   Set steering.buttons.lights flag
   * @param   value New value for the flag
   */
  void set_steering_buttons_lights(uint8_t value);

  /**
   * @brief   Set steering.buttons.cruise_control_enabled flag
   * @param   value New value for the flag
   */
  void set_steering_buttons_cruise_control_enabled(uint8_t value);

  /**
   * @brief   Set steering.buttons.hazard_enabled flag
   * @param   value New value for the flag
   */
  void set_steering_buttons_hazard_enabled(uint8_t value);

  /**
   * @brief   Set steering.buttons.horn_enabled flag
   * @param   value New value for the flag
   */
  void set_steering_buttons_horn_enabled(uint8_t value);

  /**
   * @brief   Set steering.buttons.regen_enabled flag
   * @param   value New value for the flag
   */
  void set_steering_buttons_regen_enabled(uint8_t value);

  /**
   * @brief   Set telemetry.telemetry_data (raw value)
   * @param   value New value for the signal
   */
  void set_telemetry_telemetry_data(uint64_t value);
};

/** @} */