var hierarchy =
[
    [ "_PACKED", "struct__PACKED.html", null ],
    [ "AccelGainOffsetValues", "structAccelGainOffsetValues.html", null ],
    [ "AdcStatus", "structAdcStatus.html", null ],
    [ "AuxSenseStorage", "structAuxSenseStorage.html", null ],
    [ "Axes", "structAxes.html", null ],
    [ "Bmi323Settings", "structBmi323Settings.html", null ],
    [ "Bmi323Storage", "structBmi323Storage.html", null ],
    [ "BmsConfig", "structBmsConfig.html", null ],
    [ "BmsStorage", "structBmsStorage.html", null ],
    [ "Boot_CanMessage", "structBoot__CanMessage.html", null ],
    [ "BootCanTiming", "structBootCanTiming.html", null ],
    [ "BootloaderDatagram", "structBootloaderDatagram.html", null ],
    [ "BootloaderStateData", "structBootloaderStateData.html", null ],
    [ "BufferedReader", null, [
      [ "DatagramListener", "classcan__datagram_1_1DatagramListener.html", null ]
    ] ],
    [ "CanHwTiming", "structCanHwTiming.html", null ],
    [ "CanId", "unionCanId.html", null ],
    [ "CanMessage", "structCanMessage.html", null ],
    [ "CanQueue", "structCanQueue.html", null ],
    [ "CanSettings", "structCanSettings.html", null ],
    [ "CanSimulatorDataCache", "classcan__simulator__cache_1_1CanSimulatorDataCache.html", null ],
    [ "CanStorage", "structCanStorage.html", null ],
    [ "CanWatchDog", "structCanWatchDog.html", null ],
    [ "CRC16", "classcrc_1_1CRC16.html", null ],
    [ "CRC32", "classcrc32_1_1CRC32.html", null ],
    [ "CRC32", "classcrc_1_1CRC32.html", null ],
    [ "CRC8", "classcrc_1_1CRC8.html", null ],
    [ "Datagram", "classcan__datagram_1_1Datagram.html", null ],
    [ "Datagram", "structDatagram.html", null ],
    [ "DatagramSender", "classcan__datagram_1_1DatagramSender.html", null ],
    [ "DFUStateData", "structDFUStateData.html", null ],
    [ "Exception", null, [
      [ "DatagramTypeError", "classcan__datagram_1_1DatagramTypeError.html", null ]
    ] ],
    [ "FanSettings", "structFanSettings.html", null ],
    [ "FaultBpsStorage", "structFaultBpsStorage.html", null ],
    [ "Flash_Application", "classflash__application_1_1Flash__Application.html", null ],
    [ "FotaDatagram", "structFotaDatagram.html", null ],
    [ "FotaDatagramHeaderPacketPayload", "structFotaDatagramHeaderPacketPayload.html", null ],
    [ "FotaPacket", "structFotaPacket.html", null ],
    [ "Fsm", "structFsm.html", null ],
    [ "GpioAddress", "structGpioAddress.html", null ],
    [ "GpioInterrupt", "structGpioInterrupt.html", null ],
    [ "GyroGainOffsetValues", "structGyroGainOffsetValues.html", null ],
    [ "I2CBuffer", "structI2CBuffer.html", null ],
    [ "I2CPortData", "structI2CPortData.html", null ],
    [ "I2CSettings", "structI2CSettings.html", null ],
    [ "int", null, [
      [ "SystemCanDevice", "classsystem__can_1_1SystemCanDevice.html", null ],
      [ "SystemCanMessageId", "classsystem__can_1_1SystemCanMessageId.html", null ]
    ] ],
    [ "InterruptSettings", "structInterruptSettings.html", null ],
    [ "Jump_Application", "classjump__application_1_1Jump__Application.html", null ],
    [ "Jump_Bootloader", "classjump__bootloader_1_1Jump__Bootloader.html", null ],
    [ "LtcAfeRegisterData", "unionLtcAfeRegisterData.html", null ],
    [ "LtcAfeSettings", "structLtcAfeSettings.html", null ],
    [ "LtcAfeStorage", "structLtcAfeStorage.html", null ],
    [ "Max17261Settings", "structMax17261Settings.html", null ],
    [ "Max17261Storage", "structMax17261Storage.html", null ],
    [ "Max27261Params", "structMax27261Params.html", null ],
    [ "Mcp2515Errors", "structMcp2515Errors.html", null ],
    [ "Mcp2515IdRegs", "unionMcp2515IdRegs.html", null ],
    [ "Mcp2515RxBuffer", "structMcp2515RxBuffer.html", null ],
    [ "Mcp2515Settings", "structMcp2515Settings.html", null ],
    [ "Mcp2515Storage", "structMcp2515Storage.html", null ],
    [ "Mcp2515TxBuffer", "structMcp2515TxBuffer.html", null ],
    [ "MPURegion", "structMPURegion.html", null ],
    [ "MPURegionSettings", "structMPURegionSettings.html", null ],
    [ "NetworkBuffer", "structNetworkBuffer.html", null ],
    [ "OnePedalStorage", "structOnePedalStorage.html", null ],
    [ "PacketManager", "structPacketManager.html", null ],
    [ "PedalCalibBlob", "structPedalCalibBlob.html", null ],
    [ "PedalCalibrationData", "structPedalCalibrationData.html", null ],
    [ "PedalCalibrationStorage", "structPedalCalibrationStorage.html", null ],
    [ "PersistHeader", "structPersistHeader.html", null ],
    [ "PersistStorage", "structPersistStorage.html", null ],
    [ "Ping_Application", "classping__application_1_1Ping__Application.html", null ],
    [ "PrechargeSettings", "structPrechargeSettings.html", null ],
    [ "PwmInfo", "structPwmInfo.html", null ],
    [ "Queue", "structQueue.html", null ],
    [ "RelayStorage", "structRelayStorage.html", null ],
    [ "SdSpiSettings", "structSdSpiSettings.html", null ],
    [ "Semaphore", "structSemaphore.html", null ],
    [ "SPIPortData", "structSPIPortData.html", null ],
    [ "SpiSettings", "structSpiSettings.html", null ],
    [ "State", "structState.html", null ],
    [ "StateOfChargeStorage", "structStateOfChargeStorage.html", null ],
    [ "Task", "structTask.html", null ],
    [ "TelemetryConfig", "structTelemetryConfig.html", null ],
    [ "TelemetryStorage", "structTelemetryStorage.html", null ],
    [ "TestCase", null, [
      [ "TestCanDatagram", "classtest__can__datagram_1_1TestCanDatagram.html", null ],
      [ "TestCanDatagramListener", "classtest__can__datagram_1_1TestCanDatagramListener.html", null ],
      [ "TestCanDatagramSender", "classtest__can__datagram_1_1TestCanDatagramSender.html", null ],
      [ "TestFlashApplication", "classtest__flash__application_1_1TestFlashApplication.html", null ],
      [ "TestJumpApplication", "classtest__jump__application_1_1TestJumpApplication.html", null ],
      [ "TestPingApplication", "classtest__ping__application_1_1TestPingApplication.html", null ]
    ] ],
    [ "UartPortData", "structUartPortData.html", null ],
    [ "UartSettings", "structUartSettings.html", null ],
    [ "X86Interrupt", "structX86Interrupt.html", null ],
    [ "Enum", null, [
      [ "SystemCanDevice", "classsystem__can_1_1SystemCanDevice.html", null ],
      [ "SystemCanMessageId", "classsystem__can_1_1SystemCanMessageId.html", null ]
    ] ]
];