var modules =
[
    [ "Blinky", "group__blinky.html", null ],
    [ "Bootloader", "group__bootloader.html", "group__bootloader" ],
    [ "Bootstrap", "group__bootstrap.html", null ],
    [ "FOTA", "group__FOTA.html", "group__FOTA" ],
    [ "Front_Controller", "group__Front__Controller.html", "group__Front__Controller" ],
    [ "Imu", "group__imu.html", "group__imu" ],
    [ "Rear_Controller", "group__Rear__Controller.html", "group__Rear__Controller" ],
    [ "Fans", "group__fans.html", "group__fans" ],
    [ "Steering", "group__steering.html", "group__steering" ],
    [ "Telemetry", "group__telemetry.html", "group__telemetry" ],
    [ "Can_communication", "group__can__communication.html", null ],
    [ "CAN", "group__CAN.html", "group__CAN" ],
    [ "CAN Simulation tools", "group__CANSimulator.html", "group__CANSimulator" ],
    [ "ADC", "group__ADC.html", "group__ADC" ],
    [ "CRC", "group__CRC.html", "group__CRC" ],
    [ "RTOS_Helpers", "group__RTOS__Helpers.html", "group__RTOS__Helpers" ],
    [ "Flash", "group__Flash.html", "group__Flash" ],
    [ "GlobalEnums", "group__GlobalEnums.html", "group__GlobalEnums" ],
    [ "GPIO", "group__GPIO.html", "group__GPIO" ],
    [ "I2C", "group__I2C.html", "group__I2C" ],
    [ "Interrupts", "group__Interrupts.html", "group__Interrupts" ],
    [ "Logger", "group__Logger.html", "group__Logger" ],
    [ "MCU", "group__MCU.html", "group__MCU" ],
    [ "Miscellaneous", "group__Miscellaneous.html", "group__Miscellaneous" ],
    [ "Memory_Protection_Unit", "group__Memory__Protection__Unit.html", "group__Memory__Protection__Unit" ],
    [ "Persist", "group__persist.html", "group__persist" ],
    [ "PWM", "group__PWM.html", "group__PWM" ],
    [ "SPI", "group__SPI.html", "group__SPI" ],
    [ "Status_Code", "group__Status__Code.html", "group__Status__Code" ],
    [ "UART", "group__UART.html", "group__UART" ],
    [ "ADBMS1818", "group__ADBMS1818.html", "group__ADBMS1818" ],
    [ "Current Sensing", "group__ACS37800.html", "group__ACS37800" ],
    [ "Current_acs37800_defs", "group__current__acs37800__defs.html", null ],
    [ "Max17261_fuel_gauge", "group__max17261__fuel__gauge.html", "group__max17261__fuel__gauge" ],
    [ "Max17261_fuel_gauge_defs", "group__max17261__fuel__gauge__defs.html", null ],
    [ "Pedal", "group__Pedal.html", "group__Pedal" ],
    [ "Master_Tasks", "group__Master__Tasks.html", "group__Master__Tasks" ],
    [ "Autogeneration tools", "group__autogen.html", "group__autogen" ]
];