var modules =
[
    [ "Blinky", "group__blinky.html", null ],
    [ "Bms_carrier", "group__bms__carrier.html", "group__bms__carrier" ],
    [ "Motor_controller", "group__motor__controller.html", "group__motor__controller" ],
    [ "Bootloader", "group__bootloader.html", "group__bootloader" ],
    [ "Centre_console", "group__centre__console.html", null ],
    [ "Pedal", "group__pedal.html", "group__pedal" ],
    [ "FOTA", "group__FOTA.html", "group__FOTA" ],
    [ "Imu", "group__imu.html", "group__imu" ],
    [ "Controller", "group__Rear.html", null ],
    [ "Telemetry", "group__telemetry.html", "group__telemetry" ],
    [ "Can_communication", "group__can__communication.html", null ],
    [ "CAN", "group__CAN.html", "group__CAN" ],
    [ "CAN Simulation tools", "group__CANSimulator.html", "group__CANSimulator" ],
    [ "ADC", "group__ADC.html", "group__ADC" ],
    [ "CRC", "group__CRC.html", "group__CRC" ],
    [ "RTOS_Helpers", "group__RTOS__Helpers.html", "group__RTOS__Helpers" ],
    [ "Flash", "group__Flash.html", "group__Flash" ],
    [ "Finite_State_Machine", "group__Finite__State__Machine.html", "group__Finite__State__Machine" ],
    [ "GlobalEnums", "group__GlobalEnums.html", "group__GlobalEnums" ],
    [ "GPIO", "group__GPIO.html", "group__GPIO" ],
    [ "I2C", "group__I2C.html", "group__I2C" ],
    [ "Interrupts", "group__Interrupts.html", "group__Interrupts" ],
    [ "Logger", "group__Logger.html", "group__Logger" ],
    [ "MCU", "group__MCU.html", "group__MCU" ],
    [ "Miscellaneous", "group__Miscellaneous.html", null ],
    [ "Memory_Protection_Unit", "group__Memory__Protection__Unit.html", "group__Memory__Protection__Unit" ],
    [ "Persist", "group__persist.html", "group__persist" ],
    [ "PWM", "group__PWM.html", "group__PWM" ],
    [ "SPI", "group__SPI.html", "group__SPI" ],
    [ "Status_Code", "group__Status__Code.html", "group__Status__Code" ],
    [ "UART", "group__UART.html", "group__UART" ],
    [ "LTC6811", "group__LTC6811.html", "group__LTC6811" ],
    [ "Max17261_fuel_gauge", "group__max17261__fuel__gauge.html", "group__max17261__fuel__gauge" ],
    [ "Max17261_fuel_gauge_defs", "group__max17261__fuel__gauge__defs.html", null ],
    [ "Pedal", "group__Pedal.html", "group__Pedal" ],
    [ "Master_Tasks", "group__Master__Tasks.html", "group__Master__Tasks" ],
    [ "Autogeneration tools", "group__autogen.html", "group__autogen" ]
];