#pragma once

/************************************************************************************************
 * @file    config.h
 *
 * @brief   Config
 *
 * @date    2026-03-15
 * @author  Midnight Sun Team #24 - MSXVI
 ************************************************************************************************/

/* Standard library Headers */

/* Inter-component Headers */
#include "../../lv_conf_internal.h"

/* Intra-component Headers */

/**
 * @defgroup config
 * @brief    config Firmware
 * @{
 */

/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#ifndef TVG_CONFIG_H
#define TVG_CONFIG_H

#define THORVG_SW_RASTER_SUPPORT 1

#define THORVG_SVG_LOADER_SUPPORT LV_USE_LOTTIE

#define THORVG_LOTTIE_LOADER_SUPPORT LV_USE_LOTTIE

#define THORVG_VERSION_STRING "0.15.3"

#if LV_DRAW_SW_DRAW_UNIT_CNT > 1
#define THORVG_THREAD_SUPPORT
#endif

#endif /*TVG_CONFIG_H*/

/** @} */
