/************************************************************************************************
 * @file   can_manager.cc
 *
 * @brief  Source file defining the CanManager class
 *
 * @date   2026-02-11
 * @author Midnight Sun Team #24 - MSXVI
 ************************************************************************************************/

/** @warning  This file is autogenerated */

/* Standard library Headers */
#include <iostream>
#include <string>

/* Inter-component Headers */

/* Intra-component Headers */
#include "app.h"
#include "can_manager.h"

CanManager::CanManager() : m_isRunning(false) {}

void CanManager::startSimulation() {
  if (m_isRunning) {
    std::cout << "CAN simulation already running" << std::endl;
    return;
  }

  serverCanScheduler.startCanScheduler();
  serverCanListener.listenCanBus();
  m_isRunning = true;
  std::cout << "CAN simulation started" << std::endl;
}

void CanManager::stopSimulation() {
  m_isRunning = false;
  std::cout << "CAN simulation stopped" << std::endl;
}

bool CanManager::isRunning() const {
  return m_isRunning;
}

std::vector<CanMessageInfo> CanManager::getMessageInfoList() const {
  std::vector<CanMessageInfo> list;
  {
    CanMessageInfo info;
    info.name = "fast_one_shot_msg";
    info.sender = "can_communication";
    info.id = 55U;
    info.dlc = 4U;
    info.cycle_speed = 1U;
    info.cycle = "fast";
    info.critical = false;
    info.signals.push_back({ "sig1", 16U, 0U, "standard", {} });
    info.signals.push_back({ "sig2", 16U, 16U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "medium_one_shot_msg";
    info.sender = "can_communication";
    info.id = 54U;
    info.dlc = 4U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "sig1", 16U, 0U, "standard", {} });
    info.signals.push_back({ "sig2", 16U, 16U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "slow_one_shot_msg";
    info.sender = "can_communication";
    info.id = 53U;
    info.dlc = 4U;
    info.cycle_speed = 1000U;
    info.cycle = "slow";
    info.critical = false;
    info.signals.push_back({ "sig1", 16U, 0U, "standard", {} });
    info.signals.push_back({ "sig2", 16U, 16U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "pedal";
    info.sender = "front_controller";
    info.id = 21U;
    info.dlc = 5U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "percentage", 32U, 0U, "standard", {} });
    {
      CanSignalInfo sig{ "data", 8U, 32U, "bitfield", {} };
      sig.flags.push_back({ "drive_state", 3U, 0U });
      sig.flags.push_back({ "brake_enabled", 1U, 3U });
      sig.flags.push_back({ "regen_enabled", 1U, 4U });
      info.signals.push_back(sig);
    }
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "motor_velocity";
    info.sender = "front_controller";
    info.id = 22U;
    info.dlc = 8U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "vehicle_velocity", 32U, 0U, "standard", {} });
    info.signals.push_back({ "motor_velocity", 32U, 32U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "motor_temperature";
    info.sender = "front_controller";
    info.id = 23U;
    info.dlc = 8U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "heat_sink_temp", 32U, 0U, "standard", {} });
    info.signals.push_back({ "motor_temp", 32U, 32U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "fc_power_group_a";
    info.sender = "front_controller";
    info.id = 31U;
    info.dlc = 8U;
    info.cycle_speed = 1000U;
    info.cycle = "slow";
    info.critical = false;
    info.signals.push_back({ "rev_cam_current", 16U, 0U, "standard", {} });
    info.signals.push_back({ "telem_current", 16U, 16U, "standard", {} });
    info.signals.push_back({ "steering_current", 16U, 32U, "standard", {} });
    info.signals.push_back({ "driver_fan_current", 16U, 48U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "fc_power_group_b";
    info.sender = "front_controller";
    info.id = 37U;
    info.dlc = 4U;
    info.cycle_speed = 1000U;
    info.cycle = "slow";
    info.critical = false;
    info.signals.push_back({ "horn_current", 16U, 0U, "standard", {} });
    info.signals.push_back({ "spare_current", 16U, 16U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "fc_power_lights_group";
    info.sender = "front_controller";
    info.id = 34U;
    info.dlc = 8U;
    info.cycle_speed = 1000U;
    info.cycle = "slow";
    info.critical = false;
    info.signals.push_back({ "brake_light_sig_current", 16U, 0U, "standard", {} });
    info.signals.push_back({ "bps_light_sig_current", 16U, 16U, "standard", {} });
    info.signals.push_back({ "right_sig_current", 16U, 32U, "standard", {} });
    info.signals.push_back({ "left_sig_current", 16U, 48U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "gyro_data";
    info.sender = "imu";
    info.id = 51U;
    info.dlc = 6U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "x_axis", 16U, 0U, "standard", {} });
    info.signals.push_back({ "y_axis", 16U, 16U, "standard", {} });
    info.signals.push_back({ "z_axis", 16U, 32U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "accel_data";
    info.sender = "imu";
    info.id = 50U;
    info.dlc = 6U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "x_axis", 16U, 0U, "standard", {} });
    info.signals.push_back({ "y_axis", 16U, 16U, "standard", {} });
    info.signals.push_back({ "z_axis", 16U, 32U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "rear_controller_status";
    info.sender = "rear_controller";
    info.id = 1U;
    info.dlc = 2U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = true;
    {
      CanSignalInfo sig{ "triggers", 16U, 0U, "bitfield", {} };
      sig.flags.push_back({ "bps_fault", 11U, 0U });
      sig.flags.push_back({ "relay_state", 1U, 11U });
      sig.flags.push_back({ "power_state", 1U, 12U });
      sig.flags.push_back({ "afe_status", 1U, 13U });
      sig.flags.push_back({ "motor_precharge_complete", 1U, 14U });
      info.signals.push_back(sig);
    }
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "battery_stats_a";
    info.sender = "rear_controller";
    info.id = 2U;
    info.dlc = 6U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = true;
    info.signals.push_back({ "pack_voltage", 16U, 0U, "standard", {} });
    info.signals.push_back({ "pack_current", 16U, 16U, "standard", {} });
    info.signals.push_back({ "pack_soc", 16U, 32U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "battery_stats_b";
    info.sender = "rear_controller";
    info.id = 3U;
    info.dlc = 6U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = true;
    info.signals.push_back({ "max_cell_voltage", 16U, 0U, "standard", {} });
    info.signals.push_back({ "min_cell_voltage", 16U, 16U, "standard", {} });
    info.signals.push_back({ "max_temperature", 16U, 32U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "power_input_stats";
    info.sender = "rear_controller";
    info.id = 4U;
    info.dlc = 8U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = true;
    info.signals.push_back({ "input_dcdc_voltage", 16U, 0U, "standard", {} });
    info.signals.push_back({ "input_dcdc_current", 16U, 16U, "standard", {} });
    info.signals.push_back({ "input_aux_voltage", 16U, 32U, "standard", {} });
    info.signals.push_back({ "input_aux_current", 16U, 48U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "afe1_status_a";
    info.sender = "rear_controller";
    info.id = 59U;
    info.dlc = 7U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "id", 8U, 0U, "standard", {} });
    info.signals.push_back({ "voltage_0", 16U, 8U, "standard", {} });
    info.signals.push_back({ "voltage_1", 16U, 24U, "standard", {} });
    info.signals.push_back({ "voltage_2", 16U, 40U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "afe1_status_b";
    info.sender = "rear_controller";
    info.id = 60U;
    info.dlc = 7U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "id", 8U, 0U, "standard", {} });
    info.signals.push_back({ "voltage_0", 16U, 8U, "standard", {} });
    info.signals.push_back({ "voltage_1", 16U, 24U, "standard", {} });
    info.signals.push_back({ "voltage_2", 16U, 40U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "afe2_status_a";
    info.sender = "rear_controller";
    info.id = 61U;
    info.dlc = 7U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "id", 8U, 0U, "standard", {} });
    info.signals.push_back({ "voltage_0", 16U, 8U, "standard", {} });
    info.signals.push_back({ "voltage_1", 16U, 24U, "standard", {} });
    info.signals.push_back({ "voltage_2", 16U, 40U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "afe2_status_b";
    info.sender = "rear_controller";
    info.id = 62U;
    info.dlc = 7U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "id", 8U, 0U, "standard", {} });
    info.signals.push_back({ "voltage_0", 16U, 8U, "standard", {} });
    info.signals.push_back({ "voltage_1", 16U, 24U, "standard", {} });
    info.signals.push_back({ "voltage_2", 16U, 40U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "afe_temperature";
    info.sender = "rear_controller";
    info.id = 63U;
    info.dlc = 8U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = false;
    info.signals.push_back({ "id", 8U, 0U, "standard", {} });
    info.signals.push_back({ "temperature_0", 8U, 8U, "standard", {} });
    info.signals.push_back({ "temperature_1", 8U, 16U, "standard", {} });
    info.signals.push_back({ "temperature_2", 8U, 24U, "standard", {} });
    info.signals.push_back({ "temperature_3", 8U, 32U, "standard", {} });
    info.signals.push_back({ "temperature_4", 8U, 40U, "standard", {} });
    info.signals.push_back({ "temperature_5", 8U, 48U, "standard", {} });
    info.signals.push_back({ "temperature_6", 8U, 56U, "standard", {} });
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "steering";
    info.sender = "steering";
    info.id = 6U;
    info.dlc = 5U;
    info.cycle_speed = 100U;
    info.cycle = "medium";
    info.critical = true;
    info.signals.push_back({ "cruise_control_target_velocity", 32U, 0U, "standard", {} });
    {
      CanSignalInfo sig{ "buttons", 8U, 32U, "bitfield", {} };
      sig.flags.push_back({ "drive_state", 2U, 0U });
      sig.flags.push_back({ "lights", 2U, 2U });
      sig.flags.push_back({ "cruise_control_enabled", 1U, 4U });
      sig.flags.push_back({ "hazard_enabled", 1U, 5U });
      sig.flags.push_back({ "horn_enabled", 1U, 6U });
      sig.flags.push_back({ "regen_enabled", 1U, 7U });
      info.signals.push_back(sig);
    }
    list.push_back(info);
  }
  {
    CanMessageInfo info;
    info.name = "telemetry";
    info.sender = "telemetry";
    info.id = 52U;
    info.dlc = 8U;
    info.cycle_speed = 1000U;
    info.cycle = "slow";
    info.critical = false;
    info.signals.push_back({ "telemetry_data", 64U, 0U, "standard", {} });
    list.push_back(info);
  }

  return list;
}

CanMessageInfo CanManager::getMessageInfo(const std::string &message_name) const {
  const auto list = getMessageInfoList();
  for (const auto &info : list) {
    if (info.name == message_name) {
      return info;
    }
  }
  return CanMessageInfo{};
}

nlohmann::json CanManager::getAllSignals() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY });
}

nlohmann::json CanManager::get_fast_one_shot_msg() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fast_one_shot_msg" });
}

nlohmann::json CanManager::get_medium_one_shot_msg() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "medium_one_shot_msg" });
}

nlohmann::json CanManager::get_slow_one_shot_msg() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "slow_one_shot_msg" });
}

nlohmann::json CanManager::get_pedal() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "pedal" });
}

nlohmann::json CanManager::get_motor_velocity() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "motor_velocity" });
}

nlohmann::json CanManager::get_motor_temperature() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "motor_temperature" });
}

nlohmann::json CanManager::get_fc_power_group_a() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_group_A" });
}

nlohmann::json CanManager::get_fc_power_group_b() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_group_B" });
}

nlohmann::json CanManager::get_fc_power_lights_group() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_lights_group" });
}

nlohmann::json CanManager::get_gyro_data() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "gyro_data" });
}

nlohmann::json CanManager::get_accel_data() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "accel_data" });
}

nlohmann::json CanManager::get_rear_controller_status() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "rear_controller_status" });
}

nlohmann::json CanManager::get_battery_stats_a() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "battery_stats_A" });
}

nlohmann::json CanManager::get_battery_stats_b() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "battery_stats_B" });
}

nlohmann::json CanManager::get_power_input_stats() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "power_input_stats" });
}

nlohmann::json CanManager::get_afe1_status_a() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_A" });
}

nlohmann::json CanManager::get_afe1_status_b() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_B" });
}

nlohmann::json CanManager::get_afe2_status_a() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_A" });
}

nlohmann::json CanManager::get_afe2_status_b() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_B" });
}

nlohmann::json CanManager::get_afe_temperature() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature" });
}

nlohmann::json CanManager::get_steering() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "steering" });
}

nlohmann::json CanManager::get_telemetry() const {
  return serverJSONManager.getProjectNestedValue<nlohmann::json>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "telemetry" });
}

/* Per Signal Getters */

uint16_t CanManager::get_fast_one_shot_msg_sig1() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fast_one_shot_msg", "sig1" });
}

uint16_t CanManager::get_fast_one_shot_msg_sig2() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fast_one_shot_msg", "sig2" });
}

uint16_t CanManager::get_medium_one_shot_msg_sig1() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "medium_one_shot_msg", "sig1" });
}

uint16_t CanManager::get_medium_one_shot_msg_sig2() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "medium_one_shot_msg", "sig2" });
}

uint16_t CanManager::get_slow_one_shot_msg_sig1() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "slow_one_shot_msg", "sig1" });
}

uint16_t CanManager::get_slow_one_shot_msg_sig2() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "slow_one_shot_msg", "sig2" });
}

uint32_t CanManager::get_pedal_percentage() const {
  return serverJSONManager.getProjectNestedValue<uint32_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "pedal", "percentage" });
}

uint8_t CanManager::get_pedal_data() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "pedal", "data" });
}

uint8_t CanManager::get_pedal_data_drive_state() const {
  uint8_t raw = get_pedal_data();
  return (raw >> 0U) & 0b111;
}

uint8_t CanManager::get_pedal_data_brake_enabled() const {
  uint8_t raw = get_pedal_data();
  return (raw >> 3U) & 0b1;
}

uint8_t CanManager::get_pedal_data_regen_enabled() const {
  uint8_t raw = get_pedal_data();
  return (raw >> 4U) & 0b1;
}

uint32_t CanManager::get_motor_velocity_vehicle_velocity() const {
  return serverJSONManager.getProjectNestedValue<uint32_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "motor_velocity", "vehicle_velocity" });
}

uint32_t CanManager::get_motor_velocity_motor_velocity() const {
  return serverJSONManager.getProjectNestedValue<uint32_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "motor_velocity", "motor_velocity" });
}

uint32_t CanManager::get_motor_temperature_heat_sink_temp() const {
  return serverJSONManager.getProjectNestedValue<uint32_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "motor_temperature", "heat_sink_temp" });
}

uint32_t CanManager::get_motor_temperature_motor_temp() const {
  return serverJSONManager.getProjectNestedValue<uint32_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "motor_temperature", "motor_temp" });
}

uint16_t CanManager::get_fc_power_group_a_rev_cam_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_group_A", "rev_cam_current" });
}

uint16_t CanManager::get_fc_power_group_a_telem_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_group_A", "telem_current" });
}

uint16_t CanManager::get_fc_power_group_a_steering_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_group_A", "steering_current" });
}

uint16_t CanManager::get_fc_power_group_a_driver_fan_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_group_A", "driver_fan_current" });
}

uint16_t CanManager::get_fc_power_group_b_horn_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_group_B", "horn_current" });
}

uint16_t CanManager::get_fc_power_group_b_spare_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_group_B", "spare_current" });
}

uint16_t CanManager::get_fc_power_lights_group_brake_light_sig_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_lights_group", "brake_light_sig_current" });
}

uint16_t CanManager::get_fc_power_lights_group_bps_light_sig_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_lights_group", "bps_light_sig_current" });
}

uint16_t CanManager::get_fc_power_lights_group_right_sig_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_lights_group", "right_sig_current" });
}

uint16_t CanManager::get_fc_power_lights_group_left_sig_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "fc_power_lights_group", "left_sig_current" });
}

uint16_t CanManager::get_gyro_data_x_axis() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "gyro_data", "x_axis" });
}

uint16_t CanManager::get_gyro_data_y_axis() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "gyro_data", "y_axis" });
}

uint16_t CanManager::get_gyro_data_z_axis() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "gyro_data", "z_axis" });
}

uint16_t CanManager::get_accel_data_x_axis() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "accel_data", "x_axis" });
}

uint16_t CanManager::get_accel_data_y_axis() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "accel_data", "y_axis" });
}

uint16_t CanManager::get_accel_data_z_axis() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "accel_data", "z_axis" });
}

uint16_t CanManager::get_rear_controller_status_triggers() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "rear_controller_status", "triggers" });
}

uint16_t CanManager::get_rear_controller_status_triggers_bps_fault() const {
  uint16_t raw = get_rear_controller_status_triggers();
  return (raw >> 0U) & 0b11111111111;
}

uint16_t CanManager::get_rear_controller_status_triggers_relay_state() const {
  uint16_t raw = get_rear_controller_status_triggers();
  return (raw >> 11U) & 0b1;
}

uint16_t CanManager::get_rear_controller_status_triggers_power_state() const {
  uint16_t raw = get_rear_controller_status_triggers();
  return (raw >> 12U) & 0b1;
}

uint16_t CanManager::get_rear_controller_status_triggers_afe_status() const {
  uint16_t raw = get_rear_controller_status_triggers();
  return (raw >> 13U) & 0b1;
}

uint16_t CanManager::get_rear_controller_status_triggers_motor_precharge_complete() const {
  uint16_t raw = get_rear_controller_status_triggers();
  return (raw >> 14U) & 0b1;
}

uint16_t CanManager::get_battery_stats_a_pack_voltage() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "battery_stats_A", "pack_voltage" });
}

uint16_t CanManager::get_battery_stats_a_pack_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "battery_stats_A", "pack_current" });
}

uint16_t CanManager::get_battery_stats_a_pack_soc() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "battery_stats_A", "pack_soc" });
}

uint16_t CanManager::get_battery_stats_b_max_cell_voltage() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "battery_stats_B", "max_cell_voltage" });
}

uint16_t CanManager::get_battery_stats_b_min_cell_voltage() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "battery_stats_B", "min_cell_voltage" });
}

uint16_t CanManager::get_battery_stats_b_max_temperature() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "battery_stats_B", "max_temperature" });
}

uint16_t CanManager::get_power_input_stats_input_dcdc_voltage() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "power_input_stats", "input_dcdc_voltage" });
}

uint16_t CanManager::get_power_input_stats_input_dcdc_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "power_input_stats", "input_dcdc_current" });
}

uint16_t CanManager::get_power_input_stats_input_aux_voltage() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "power_input_stats", "input_aux_voltage" });
}

uint16_t CanManager::get_power_input_stats_input_aux_current() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "power_input_stats", "input_aux_current" });
}

uint8_t CanManager::get_afe1_status_a_id() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_A", "id" });
}

uint16_t CanManager::get_afe1_status_a_voltage_0() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_A", "voltage_0" });
}

uint16_t CanManager::get_afe1_status_a_voltage_1() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_A", "voltage_1" });
}

uint16_t CanManager::get_afe1_status_a_voltage_2() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_A", "voltage_2" });
}

uint8_t CanManager::get_afe1_status_b_id() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_B", "id" });
}

uint16_t CanManager::get_afe1_status_b_voltage_0() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_B", "voltage_0" });
}

uint16_t CanManager::get_afe1_status_b_voltage_1() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_B", "voltage_1" });
}

uint16_t CanManager::get_afe1_status_b_voltage_2() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE1_status_B", "voltage_2" });
}

uint8_t CanManager::get_afe2_status_a_id() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_A", "id" });
}

uint16_t CanManager::get_afe2_status_a_voltage_0() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_A", "voltage_0" });
}

uint16_t CanManager::get_afe2_status_a_voltage_1() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_A", "voltage_1" });
}

uint16_t CanManager::get_afe2_status_a_voltage_2() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_A", "voltage_2" });
}

uint8_t CanManager::get_afe2_status_b_id() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_B", "id" });
}

uint16_t CanManager::get_afe2_status_b_voltage_0() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_B", "voltage_0" });
}

uint16_t CanManager::get_afe2_status_b_voltage_1() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_B", "voltage_1" });
}

uint16_t CanManager::get_afe2_status_b_voltage_2() const {
  return serverJSONManager.getProjectNestedValue<uint16_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE2_status_B", "voltage_2" });
}

uint8_t CanManager::get_afe_temperature_id() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature", "id" });
}

uint8_t CanManager::get_afe_temperature_temperature_0() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature", "temperature_0" });
}

uint8_t CanManager::get_afe_temperature_temperature_1() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature", "temperature_1" });
}

uint8_t CanManager::get_afe_temperature_temperature_2() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature", "temperature_2" });
}

uint8_t CanManager::get_afe_temperature_temperature_3() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature", "temperature_3" });
}

uint8_t CanManager::get_afe_temperature_temperature_4() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature", "temperature_4" });
}

uint8_t CanManager::get_afe_temperature_temperature_5() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature", "temperature_5" });
}

uint8_t CanManager::get_afe_temperature_temperature_6() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "AFE_temperature", "temperature_6" });
}

uint32_t CanManager::get_steering_cruise_control_target_velocity() const {
  return serverJSONManager.getProjectNestedValue<uint32_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "steering", "cruise_control_target_velocity" });
}

uint8_t CanManager::get_steering_buttons() const {
  return serverJSONManager.getProjectNestedValue<uint8_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "steering", "buttons" });
}

uint8_t CanManager::get_steering_buttons_drive_state() const {
  uint8_t raw = get_steering_buttons();
  return (raw >> 0U) & 0b11;
}

uint8_t CanManager::get_steering_buttons_lights() const {
  uint8_t raw = get_steering_buttons();
  return (raw >> 2U) & 0b11;
}

uint8_t CanManager::get_steering_buttons_cruise_control_enabled() const {
  uint8_t raw = get_steering_buttons();
  return (raw >> 4U) & 0b1;
}

uint8_t CanManager::get_steering_buttons_hazard_enabled() const {
  uint8_t raw = get_steering_buttons();
  return (raw >> 5U) & 0b1;
}

uint8_t CanManager::get_steering_buttons_horn_enabled() const {
  uint8_t raw = get_steering_buttons();
  return (raw >> 6U) & 0b1;
}

uint8_t CanManager::get_steering_buttons_regen_enabled() const {
  uint8_t raw = get_steering_buttons();
  return (raw >> 7U) & 0b1;
}

uint64_t CanManager::get_telemetry_telemetry_data() const {
  return serverJSONManager.getProjectNestedValue<uint64_t>(CAN_JSON_PROJECT, { CAN_JSON_MESSAGES_KEY, "telemetry", "telemetry_data" });
}

/* Per Signal Setters*/

void CanManager::set_fast_one_shot_msg_sig1(uint16_t value) {
  serverCanScheduler.update_fast_one_shot_msg_sig1(value);
}

void CanManager::set_fast_one_shot_msg_sig2(uint16_t value) {
  serverCanScheduler.update_fast_one_shot_msg_sig2(value);
}

void CanManager::set_medium_one_shot_msg_sig1(uint16_t value) {
  serverCanScheduler.update_medium_one_shot_msg_sig1(value);
}

void CanManager::set_medium_one_shot_msg_sig2(uint16_t value) {
  serverCanScheduler.update_medium_one_shot_msg_sig2(value);
}

void CanManager::set_slow_one_shot_msg_sig1(uint16_t value) {
  serverCanScheduler.update_slow_one_shot_msg_sig1(value);
}

void CanManager::set_slow_one_shot_msg_sig2(uint16_t value) {
  serverCanScheduler.update_slow_one_shot_msg_sig2(value);
}

void CanManager::set_pedal_percentage(uint32_t value) {
  serverCanScheduler.update_pedal_percentage(value);
}

void CanManager::set_pedal_data(uint8_t value) {
  serverCanScheduler.update_pedal_data(value);
}

void CanManager::set_pedal_data_drive_state(uint8_t value) {
  uint8_t raw = get_pedal_data();
  raw = (raw & ~(static_cast<uint8_t>(0b111) << 0U)) | ((value & 0b111) << 0U);
  serverCanScheduler.update_pedal_data(raw);
}

void CanManager::set_pedal_data_brake_enabled(uint8_t value) {
  uint8_t raw = get_pedal_data();
  raw = (raw & ~(static_cast<uint8_t>(0b1) << 3U)) | ((value & 0b1) << 3U);
  serverCanScheduler.update_pedal_data(raw);
}

void CanManager::set_pedal_data_regen_enabled(uint8_t value) {
  uint8_t raw = get_pedal_data();
  raw = (raw & ~(static_cast<uint8_t>(0b1) << 4U)) | ((value & 0b1) << 4U);
  serverCanScheduler.update_pedal_data(raw);
}

void CanManager::set_motor_velocity_vehicle_velocity(uint32_t value) {
  serverCanScheduler.update_motor_velocity_vehicle_velocity(value);
}

void CanManager::set_motor_velocity_motor_velocity(uint32_t value) {
  serverCanScheduler.update_motor_velocity_motor_velocity(value);
}

void CanManager::set_motor_temperature_heat_sink_temp(uint32_t value) {
  serverCanScheduler.update_motor_temperature_heat_sink_temp(value);
}

void CanManager::set_motor_temperature_motor_temp(uint32_t value) {
  serverCanScheduler.update_motor_temperature_motor_temp(value);
}

void CanManager::set_fc_power_group_a_rev_cam_current(uint16_t value) {
  serverCanScheduler.update_fc_power_group_a_rev_cam_current(value);
}

void CanManager::set_fc_power_group_a_telem_current(uint16_t value) {
  serverCanScheduler.update_fc_power_group_a_telem_current(value);
}

void CanManager::set_fc_power_group_a_steering_current(uint16_t value) {
  serverCanScheduler.update_fc_power_group_a_steering_current(value);
}

void CanManager::set_fc_power_group_a_driver_fan_current(uint16_t value) {
  serverCanScheduler.update_fc_power_group_a_driver_fan_current(value);
}

void CanManager::set_fc_power_group_b_horn_current(uint16_t value) {
  serverCanScheduler.update_fc_power_group_b_horn_current(value);
}

void CanManager::set_fc_power_group_b_spare_current(uint16_t value) {
  serverCanScheduler.update_fc_power_group_b_spare_current(value);
}

void CanManager::set_fc_power_lights_group_brake_light_sig_current(uint16_t value) {
  serverCanScheduler.update_fc_power_lights_group_brake_light_sig_current(value);
}

void CanManager::set_fc_power_lights_group_bps_light_sig_current(uint16_t value) {
  serverCanScheduler.update_fc_power_lights_group_bps_light_sig_current(value);
}

void CanManager::set_fc_power_lights_group_right_sig_current(uint16_t value) {
  serverCanScheduler.update_fc_power_lights_group_right_sig_current(value);
}

void CanManager::set_fc_power_lights_group_left_sig_current(uint16_t value) {
  serverCanScheduler.update_fc_power_lights_group_left_sig_current(value);
}

void CanManager::set_gyro_data_x_axis(uint16_t value) {
  serverCanScheduler.update_gyro_data_x_axis(value);
}

void CanManager::set_gyro_data_y_axis(uint16_t value) {
  serverCanScheduler.update_gyro_data_y_axis(value);
}

void CanManager::set_gyro_data_z_axis(uint16_t value) {
  serverCanScheduler.update_gyro_data_z_axis(value);
}

void CanManager::set_accel_data_x_axis(uint16_t value) {
  serverCanScheduler.update_accel_data_x_axis(value);
}

void CanManager::set_accel_data_y_axis(uint16_t value) {
  serverCanScheduler.update_accel_data_y_axis(value);
}

void CanManager::set_accel_data_z_axis(uint16_t value) {
  serverCanScheduler.update_accel_data_z_axis(value);
}

void CanManager::set_rear_controller_status_triggers(uint16_t value) {
  serverCanScheduler.update_rear_controller_status_triggers(value);
}

void CanManager::set_rear_controller_status_triggers_bps_fault(uint16_t value) {
  uint16_t raw = get_rear_controller_status_triggers();
  raw = (raw & ~(static_cast<uint16_t>(0b11111111111) << 0U)) | ((value & 0b11111111111) << 0U);
  serverCanScheduler.update_rear_controller_status_triggers(raw);
}

void CanManager::set_rear_controller_status_triggers_relay_state(uint16_t value) {
  uint16_t raw = get_rear_controller_status_triggers();
  raw = (raw & ~(static_cast<uint16_t>(0b1) << 11U)) | ((value & 0b1) << 11U);
  serverCanScheduler.update_rear_controller_status_triggers(raw);
}

void CanManager::set_rear_controller_status_triggers_power_state(uint16_t value) {
  uint16_t raw = get_rear_controller_status_triggers();
  raw = (raw & ~(static_cast<uint16_t>(0b1) << 12U)) | ((value & 0b1) << 12U);
  serverCanScheduler.update_rear_controller_status_triggers(raw);
}

void CanManager::set_rear_controller_status_triggers_afe_status(uint16_t value) {
  uint16_t raw = get_rear_controller_status_triggers();
  raw = (raw & ~(static_cast<uint16_t>(0b1) << 13U)) | ((value & 0b1) << 13U);
  serverCanScheduler.update_rear_controller_status_triggers(raw);
}

void CanManager::set_rear_controller_status_triggers_motor_precharge_complete(uint16_t value) {
  uint16_t raw = get_rear_controller_status_triggers();
  raw = (raw & ~(static_cast<uint16_t>(0b1) << 14U)) | ((value & 0b1) << 14U);
  serverCanScheduler.update_rear_controller_status_triggers(raw);
}

void CanManager::set_battery_stats_a_pack_voltage(uint16_t value) {
  serverCanScheduler.update_battery_stats_a_pack_voltage(value);
}

void CanManager::set_battery_stats_a_pack_current(uint16_t value) {
  serverCanScheduler.update_battery_stats_a_pack_current(value);
}

void CanManager::set_battery_stats_a_pack_soc(uint16_t value) {
  serverCanScheduler.update_battery_stats_a_pack_soc(value);
}

void CanManager::set_battery_stats_b_max_cell_voltage(uint16_t value) {
  serverCanScheduler.update_battery_stats_b_max_cell_voltage(value);
}

void CanManager::set_battery_stats_b_min_cell_voltage(uint16_t value) {
  serverCanScheduler.update_battery_stats_b_min_cell_voltage(value);
}

void CanManager::set_battery_stats_b_max_temperature(uint16_t value) {
  serverCanScheduler.update_battery_stats_b_max_temperature(value);
}

void CanManager::set_power_input_stats_input_dcdc_voltage(uint16_t value) {
  serverCanScheduler.update_power_input_stats_input_dcdc_voltage(value);
}

void CanManager::set_power_input_stats_input_dcdc_current(uint16_t value) {
  serverCanScheduler.update_power_input_stats_input_dcdc_current(value);
}

void CanManager::set_power_input_stats_input_aux_voltage(uint16_t value) {
  serverCanScheduler.update_power_input_stats_input_aux_voltage(value);
}

void CanManager::set_power_input_stats_input_aux_current(uint16_t value) {
  serverCanScheduler.update_power_input_stats_input_aux_current(value);
}

void CanManager::set_afe1_status_a_id(uint8_t value) {
  serverCanScheduler.update_afe1_status_a_id(value);
}

void CanManager::set_afe1_status_a_voltage_0(uint16_t value) {
  serverCanScheduler.update_afe1_status_a_voltage_0(value);
}

void CanManager::set_afe1_status_a_voltage_1(uint16_t value) {
  serverCanScheduler.update_afe1_status_a_voltage_1(value);
}

void CanManager::set_afe1_status_a_voltage_2(uint16_t value) {
  serverCanScheduler.update_afe1_status_a_voltage_2(value);
}

void CanManager::set_afe1_status_b_id(uint8_t value) {
  serverCanScheduler.update_afe1_status_b_id(value);
}

void CanManager::set_afe1_status_b_voltage_0(uint16_t value) {
  serverCanScheduler.update_afe1_status_b_voltage_0(value);
}

void CanManager::set_afe1_status_b_voltage_1(uint16_t value) {
  serverCanScheduler.update_afe1_status_b_voltage_1(value);
}

void CanManager::set_afe1_status_b_voltage_2(uint16_t value) {
  serverCanScheduler.update_afe1_status_b_voltage_2(value);
}

void CanManager::set_afe2_status_a_id(uint8_t value) {
  serverCanScheduler.update_afe2_status_a_id(value);
}

void CanManager::set_afe2_status_a_voltage_0(uint16_t value) {
  serverCanScheduler.update_afe2_status_a_voltage_0(value);
}

void CanManager::set_afe2_status_a_voltage_1(uint16_t value) {
  serverCanScheduler.update_afe2_status_a_voltage_1(value);
}

void CanManager::set_afe2_status_a_voltage_2(uint16_t value) {
  serverCanScheduler.update_afe2_status_a_voltage_2(value);
}

void CanManager::set_afe2_status_b_id(uint8_t value) {
  serverCanScheduler.update_afe2_status_b_id(value);
}

void CanManager::set_afe2_status_b_voltage_0(uint16_t value) {
  serverCanScheduler.update_afe2_status_b_voltage_0(value);
}

void CanManager::set_afe2_status_b_voltage_1(uint16_t value) {
  serverCanScheduler.update_afe2_status_b_voltage_1(value);
}

void CanManager::set_afe2_status_b_voltage_2(uint16_t value) {
  serverCanScheduler.update_afe2_status_b_voltage_2(value);
}

void CanManager::set_afe_temperature_id(uint8_t value) {
  serverCanScheduler.update_afe_temperature_id(value);
}

void CanManager::set_afe_temperature_temperature_0(uint8_t value) {
  serverCanScheduler.update_afe_temperature_temperature_0(value);
}

void CanManager::set_afe_temperature_temperature_1(uint8_t value) {
  serverCanScheduler.update_afe_temperature_temperature_1(value);
}

void CanManager::set_afe_temperature_temperature_2(uint8_t value) {
  serverCanScheduler.update_afe_temperature_temperature_2(value);
}

void CanManager::set_afe_temperature_temperature_3(uint8_t value) {
  serverCanScheduler.update_afe_temperature_temperature_3(value);
}

void CanManager::set_afe_temperature_temperature_4(uint8_t value) {
  serverCanScheduler.update_afe_temperature_temperature_4(value);
}

void CanManager::set_afe_temperature_temperature_5(uint8_t value) {
  serverCanScheduler.update_afe_temperature_temperature_5(value);
}

void CanManager::set_afe_temperature_temperature_6(uint8_t value) {
  serverCanScheduler.update_afe_temperature_temperature_6(value);
}

void CanManager::set_steering_cruise_control_target_velocity(uint32_t value) {
  serverCanScheduler.update_steering_cruise_control_target_velocity(value);
}

void CanManager::set_steering_buttons(uint8_t value) {
  serverCanScheduler.update_steering_buttons(value);
}

void CanManager::set_steering_buttons_drive_state(uint8_t value) {
  uint8_t raw = get_steering_buttons();
  raw = (raw & ~(static_cast<uint8_t>(0b11) << 0U)) | ((value & 0b11) << 0U);
  serverCanScheduler.update_steering_buttons(raw);
}

void CanManager::set_steering_buttons_lights(uint8_t value) {
  uint8_t raw = get_steering_buttons();
  raw = (raw & ~(static_cast<uint8_t>(0b11) << 2U)) | ((value & 0b11) << 2U);
  serverCanScheduler.update_steering_buttons(raw);
}

void CanManager::set_steering_buttons_cruise_control_enabled(uint8_t value) {
  uint8_t raw = get_steering_buttons();
  raw = (raw & ~(static_cast<uint8_t>(0b1) << 4U)) | ((value & 0b1) << 4U);
  serverCanScheduler.update_steering_buttons(raw);
}

void CanManager::set_steering_buttons_hazard_enabled(uint8_t value) {
  uint8_t raw = get_steering_buttons();
  raw = (raw & ~(static_cast<uint8_t>(0b1) << 5U)) | ((value & 0b1) << 5U);
  serverCanScheduler.update_steering_buttons(raw);
}

void CanManager::set_steering_buttons_horn_enabled(uint8_t value) {
  uint8_t raw = get_steering_buttons();
  raw = (raw & ~(static_cast<uint8_t>(0b1) << 6U)) | ((value & 0b1) << 6U);
  serverCanScheduler.update_steering_buttons(raw);
}

void CanManager::set_steering_buttons_regen_enabled(uint8_t value) {
  uint8_t raw = get_steering_buttons();
  raw = (raw & ~(static_cast<uint8_t>(0b1) << 7U)) | ((value & 0b1) << 7U);
  serverCanScheduler.update_steering_buttons(raw);
}

void CanManager::set_telemetry_telemetry_data(uint64_t value) {
  serverCanScheduler.update_telemetry_telemetry_data(value);
}
