/************************************************************************************************
 * @file   can_message_handler.cc
 *
 * @brief  Source file defining the Can Message Handler function
 *
 * @date   2026-04-02
 * @author Aryan Kashem
 ************************************************************************************************/

/** @warning  This file is autogenerated */

/* Standard library Headers */
#include <iostream>
#include <unordered_map>
#include <string>
#include <cstdint>

/* Inter-component Headers */
#include <nlohmann/json.hpp>

#include "system_can.h"

/* Intra-component Headers */
#include "can_listener.h"


/**
 * @brief   Storage class for fast_one_shot_msg CAN message
 */
struct fast_one_shot_msg {
  uint16_t sig1; /**< CAN signal 'sig1' defined in *.yaml */
  uint16_t sig2; /**< CAN signal 'sig2' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for fast_one_shot_msg
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      sig1 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      sig2 = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for fast_one_shot_msg using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"sig1", sig1},
      {"sig2", sig2}
    };
  }

  /**
   * @brief   Get the message name: fast_one_shot_msg
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "fast_one_shot_msg";
  }
};
/**
 * @brief   Storage class for medium_one_shot_msg CAN message
 */
struct medium_one_shot_msg {
  uint16_t sig1; /**< CAN signal 'sig1' defined in *.yaml */
  uint16_t sig2; /**< CAN signal 'sig2' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for medium_one_shot_msg
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      sig1 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      sig2 = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for medium_one_shot_msg using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"sig1", sig1},
      {"sig2", sig2}
    };
  }

  /**
   * @brief   Get the message name: medium_one_shot_msg
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "medium_one_shot_msg";
  }
};
/**
 * @brief   Storage class for slow_one_shot_msg CAN message
 */
struct slow_one_shot_msg {
  uint16_t sig1; /**< CAN signal 'sig1' defined in *.yaml */
  uint16_t sig2; /**< CAN signal 'sig2' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for slow_one_shot_msg
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      sig1 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      sig2 = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for slow_one_shot_msg using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"sig1", sig1},
      {"sig2", sig2}
    };
  }

  /**
   * @brief   Get the message name: slow_one_shot_msg
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "slow_one_shot_msg";
  }
};
/**
 * @brief   Storage class for drive_status CAN message
 */
struct drive_status {
  uint32_t pedal_percentage; /**< CAN signal 'pedal_percentage' defined in *.yaml */
  uint8_t state_data; /**< CAN signal 'state_data' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for drive_status
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 2]) << 16U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 3]) << 24U;
      
      pedal_percentage = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      state_data = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for drive_status using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"pedal_percentage", pedal_percentage},
      {"state_data", state_data}
    };
  }

  /**
   * @brief   Get the message name: drive_status
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "drive_status";
  }
};
/**
 * @brief   Storage class for motor_stats_a CAN message
 */
struct motor_stats_a {
  uint16_t bus_voltage; /**< CAN signal 'bus_voltage' defined in *.yaml */
  uint16_t bus_current; /**< CAN signal 'bus_current' defined in *.yaml */
  uint16_t rail_15v_supply; /**< CAN signal 'rail_15v_supply' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for motor_stats_A
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      bus_voltage = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      bus_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      rail_15v_supply = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for motor_stats_A using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"bus_voltage", bus_voltage},
      {"bus_current", bus_current},
      {"rail_15v_supply", rail_15v_supply}
    };
  }

  /**
   * @brief   Get the message name: motor_stats_A
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "motor_stats_A";
  }
};
/**
 * @brief   Storage class for motor_stats_b CAN message
 */
struct motor_stats_b {
  uint16_t vehicle_velocity; /**< CAN signal 'vehicle_velocity' defined in *.yaml */
  uint16_t motor_velocity; /**< CAN signal 'motor_velocity' defined in *.yaml */
  uint16_t heat_sink_temp; /**< CAN signal 'heat_sink_temp' defined in *.yaml */
  uint16_t motor_temp; /**< CAN signal 'motor_temp' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for motor_stats_B
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      vehicle_velocity = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      motor_velocity = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      heat_sink_temp = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 6;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      motor_temp = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for motor_stats_B using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"vehicle_velocity", vehicle_velocity},
      {"motor_velocity", motor_velocity},
      {"heat_sink_temp", heat_sink_temp},
      {"motor_temp", motor_temp}
    };
  }

  /**
   * @brief   Get the message name: motor_stats_B
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "motor_stats_B";
  }
};
/**
 * @brief   Storage class for fc_power_group_a CAN message
 */
struct fc_power_group_a {
  uint16_t rev_cam_current; /**< CAN signal 'rev_cam_current' defined in *.yaml */
  uint16_t telem_current; /**< CAN signal 'telem_current' defined in *.yaml */
  uint16_t steering_current; /**< CAN signal 'steering_current' defined in *.yaml */
  uint16_t driver_fan_current; /**< CAN signal 'driver_fan_current' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for fc_power_group_A
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      rev_cam_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      telem_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      steering_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 6;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      driver_fan_current = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for fc_power_group_A using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"rev_cam_current", rev_cam_current},
      {"telem_current", telem_current},
      {"steering_current", steering_current},
      {"driver_fan_current", driver_fan_current}
    };
  }

  /**
   * @brief   Get the message name: fc_power_group_A
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "fc_power_group_A";
  }
};
/**
 * @brief   Storage class for fc_power_group_b CAN message
 */
struct fc_power_group_b {
  uint16_t horn_current; /**< CAN signal 'horn_current' defined in *.yaml */
  uint16_t spare_current; /**< CAN signal 'spare_current' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for fc_power_group_B
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      horn_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      spare_current = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for fc_power_group_B using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"horn_current", horn_current},
      {"spare_current", spare_current}
    };
  }

  /**
   * @brief   Get the message name: fc_power_group_B
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "fc_power_group_B";
  }
};
/**
 * @brief   Storage class for fc_power_lights_group CAN message
 */
struct fc_power_lights_group {
  uint16_t brake_light_sig_current; /**< CAN signal 'brake_light_sig_current' defined in *.yaml */
  uint16_t bps_light_sig_current; /**< CAN signal 'bps_light_sig_current' defined in *.yaml */
  uint16_t right_sig_current; /**< CAN signal 'right_sig_current' defined in *.yaml */
  uint16_t left_sig_current; /**< CAN signal 'left_sig_current' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for fc_power_lights_group
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      brake_light_sig_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      bps_light_sig_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      right_sig_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 6;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      left_sig_current = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for fc_power_lights_group using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"brake_light_sig_current", brake_light_sig_current},
      {"bps_light_sig_current", bps_light_sig_current},
      {"right_sig_current", right_sig_current},
      {"left_sig_current", left_sig_current}
    };
  }

  /**
   * @brief   Get the message name: fc_power_lights_group
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "fc_power_lights_group";
  }
};
/**
 * @brief   Storage class for gyro_data CAN message
 */
struct gyro_data {
  uint16_t x_axis; /**< CAN signal 'x_axis' defined in *.yaml */
  uint16_t y_axis; /**< CAN signal 'y_axis' defined in *.yaml */
  uint16_t z_axis; /**< CAN signal 'z_axis' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for gyro_data
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      x_axis = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      y_axis = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      z_axis = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for gyro_data using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"x_axis", x_axis},
      {"y_axis", y_axis},
      {"z_axis", z_axis}
    };
  }

  /**
   * @brief   Get the message name: gyro_data
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "gyro_data";
  }
};
/**
 * @brief   Storage class for accel_data CAN message
 */
struct accel_data {
  uint16_t x_axis; /**< CAN signal 'x_axis' defined in *.yaml */
  uint16_t y_axis; /**< CAN signal 'y_axis' defined in *.yaml */
  uint16_t z_axis; /**< CAN signal 'z_axis' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for accel_data
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      x_axis = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      y_axis = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      z_axis = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for accel_data using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"x_axis", x_axis},
      {"y_axis", y_axis},
      {"z_axis", z_axis}
    };
  }

  /**
   * @brief   Get the message name: accel_data
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "accel_data";
  }
};
/**
 * @brief   Storage class for rear_controller_status CAN message
 */
struct rear_controller_status {
  uint8_t triggers; /**< CAN signal 'triggers' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for rear_controller_status
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      triggers = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for rear_controller_status using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"triggers", triggers}
    };
  }

  /**
   * @brief   Get the message name: rear_controller_status
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "rear_controller_status";
  }
};
/**
 * @brief   Storage class for battery_stats_a CAN message
 */
struct battery_stats_a {
  uint16_t pack_voltage; /**< CAN signal 'pack_voltage' defined in *.yaml */
  uint16_t pack_current; /**< CAN signal 'pack_current' defined in *.yaml */
  uint16_t pack_soc; /**< CAN signal 'pack_soc' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for battery_stats_A
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      pack_voltage = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      pack_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      pack_soc = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for battery_stats_A using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"pack_voltage", pack_voltage},
      {"pack_current", pack_current},
      {"pack_soc", pack_soc}
    };
  }

  /**
   * @brief   Get the message name: battery_stats_A
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "battery_stats_A";
  }
};
/**
 * @brief   Storage class for battery_stats_b CAN message
 */
struct battery_stats_b {
  uint16_t max_cell_voltage; /**< CAN signal 'max_cell_voltage' defined in *.yaml */
  uint16_t min_cell_voltage; /**< CAN signal 'min_cell_voltage' defined in *.yaml */
  uint16_t max_temperature; /**< CAN signal 'max_temperature' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for battery_stats_B
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      max_cell_voltage = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      min_cell_voltage = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      max_temperature = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for battery_stats_B using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"max_cell_voltage", max_cell_voltage},
      {"min_cell_voltage", min_cell_voltage},
      {"max_temperature", max_temperature}
    };
  }

  /**
   * @brief   Get the message name: battery_stats_B
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "battery_stats_B";
  }
};
/**
 * @brief   Storage class for power_input_stats CAN message
 */
struct power_input_stats {
  uint16_t input_dcdc_voltage; /**< CAN signal 'input_dcdc_voltage' defined in *.yaml */
  uint16_t input_dcdc_current; /**< CAN signal 'input_dcdc_current' defined in *.yaml */
  uint16_t input_aux_voltage; /**< CAN signal 'input_aux_voltage' defined in *.yaml */
  uint16_t input_aux_current; /**< CAN signal 'input_aux_current' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for power_input_stats
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      input_dcdc_voltage = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      input_dcdc_current = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      input_aux_voltage = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 6;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      input_aux_current = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for power_input_stats using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"input_dcdc_voltage", input_dcdc_voltage},
      {"input_dcdc_current", input_dcdc_current},
      {"input_aux_voltage", input_aux_voltage},
      {"input_aux_current", input_aux_current}
    };
  }

  /**
   * @brief   Get the message name: power_input_stats
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "power_input_stats";
  }
};
/**
 * @brief   Storage class for afe1_status_a CAN message
 */
struct afe1_status_a {
  uint8_t id; /**< CAN signal 'id' defined in *.yaml */
  uint16_t voltage_0; /**< CAN signal 'voltage_0' defined in *.yaml */
  uint16_t voltage_1; /**< CAN signal 'voltage_1' defined in *.yaml */
  uint16_t voltage_2; /**< CAN signal 'voltage_2' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for AFE1_status_A
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      id = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 1;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_0 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 3;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_1 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 5;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_2 = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for AFE1_status_A using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"id", id},
      {"voltage_0", voltage_0},
      {"voltage_1", voltage_1},
      {"voltage_2", voltage_2}
    };
  }

  /**
   * @brief   Get the message name: AFE1_status_A
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "AFE1_status_A";
  }
};
/**
 * @brief   Storage class for afe1_status_b CAN message
 */
struct afe1_status_b {
  uint8_t id; /**< CAN signal 'id' defined in *.yaml */
  uint16_t voltage_0; /**< CAN signal 'voltage_0' defined in *.yaml */
  uint16_t voltage_1; /**< CAN signal 'voltage_1' defined in *.yaml */
  uint16_t voltage_2; /**< CAN signal 'voltage_2' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for AFE1_status_B
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      id = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 1;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_0 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 3;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_1 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 5;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_2 = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for AFE1_status_B using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"id", id},
      {"voltage_0", voltage_0},
      {"voltage_1", voltage_1},
      {"voltage_2", voltage_2}
    };
  }

  /**
   * @brief   Get the message name: AFE1_status_B
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "AFE1_status_B";
  }
};
/**
 * @brief   Storage class for afe2_status_a CAN message
 */
struct afe2_status_a {
  uint8_t id; /**< CAN signal 'id' defined in *.yaml */
  uint16_t voltage_0; /**< CAN signal 'voltage_0' defined in *.yaml */
  uint16_t voltage_1; /**< CAN signal 'voltage_1' defined in *.yaml */
  uint16_t voltage_2; /**< CAN signal 'voltage_2' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for AFE2_status_A
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      id = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 1;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_0 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 3;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_1 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 5;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_2 = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for AFE2_status_A using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"id", id},
      {"voltage_0", voltage_0},
      {"voltage_1", voltage_1},
      {"voltage_2", voltage_2}
    };
  }

  /**
   * @brief   Get the message name: AFE2_status_A
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "AFE2_status_A";
  }
};
/**
 * @brief   Storage class for afe2_status_b CAN message
 */
struct afe2_status_b {
  uint8_t id; /**< CAN signal 'id' defined in *.yaml */
  uint16_t voltage_0; /**< CAN signal 'voltage_0' defined in *.yaml */
  uint16_t voltage_1; /**< CAN signal 'voltage_1' defined in *.yaml */
  uint16_t voltage_2; /**< CAN signal 'voltage_2' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for AFE2_status_B
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      id = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 1;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_0 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 3;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_1 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 5;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      voltage_2 = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for AFE2_status_B using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"id", id},
      {"voltage_0", voltage_0},
      {"voltage_1", voltage_1},
      {"voltage_2", voltage_2}
    };
  }

  /**
   * @brief   Get the message name: AFE2_status_B
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "AFE2_status_B";
  }
};
/**
 * @brief   Storage class for afe_temperature CAN message
 */
struct afe_temperature {
  uint8_t id; /**< CAN signal 'id' defined in *.yaml */
  uint8_t temperature_0; /**< CAN signal 'temperature_0' defined in *.yaml */
  uint8_t temperature_1; /**< CAN signal 'temperature_1' defined in *.yaml */
  uint8_t temperature_2; /**< CAN signal 'temperature_2' defined in *.yaml */
  uint8_t temperature_3; /**< CAN signal 'temperature_3' defined in *.yaml */
  uint8_t temperature_4; /**< CAN signal 'temperature_4' defined in *.yaml */
  uint8_t temperature_5; /**< CAN signal 'temperature_5' defined in *.yaml */
  uint8_t temperature_6; /**< CAN signal 'temperature_6' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for AFE_temperature
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      id = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 1;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      temperature_0 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      temperature_1 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 3;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      temperature_2 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      temperature_3 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 5;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      temperature_4 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 6;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      temperature_5 = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 7;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      temperature_6 = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for AFE_temperature using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"id", id},
      {"temperature_0", temperature_0},
      {"temperature_1", temperature_1},
      {"temperature_2", temperature_2},
      {"temperature_3", temperature_3},
      {"temperature_4", temperature_4},
      {"temperature_5", temperature_5},
      {"temperature_6", temperature_6}
    };
  }

  /**
   * @brief   Get the message name: AFE_temperature
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "AFE_temperature";
  }
};
/**
 * @brief   Storage class for steering CAN message
 */
struct steering {
  uint32_t cruise_control_target_velocity; /**< CAN signal 'cruise_control_target_velocity' defined in *.yaml */
  uint8_t buttons; /**< CAN signal 'buttons' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for steering
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 2]) << 16U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 3]) << 24U;
      
      cruise_control_target_velocity = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      
      buttons = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for steering using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"cruise_control_target_velocity", cruise_control_target_velocity},
      {"buttons", buttons}
    };
  }

  /**
   * @brief   Get the message name: steering
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "steering";
  }
};
/**
 * @brief   Storage class for imu_data CAN message
 */
struct imu_data {
  uint16_t g_force; /**< CAN signal 'g_force' defined in *.yaml */
  uint16_t roll; /**< CAN signal 'roll' defined in *.yaml */
  uint16_t pitch; /**< CAN signal 'pitch' defined in *.yaml */
  uint16_t yaw; /**< CAN signal 'yaw' defined in *.yaml */

  /**
   * @brief   Decode new CAN data and update the storage for imu_data
   * @param   data Pointer to the CAN message to be decoded
   */
  void decode(const uint8_t *data) {
    uint64_t raw_val = 0U;
    uint8_t start_byte = 0U;
    {
      raw_val = 0U;
      start_byte = 0;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      g_force = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 2;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      roll = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 4;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      pitch = raw_val;
    }
    {
      raw_val = 0U;
      start_byte = 6;
      raw_val |= static_cast<uint64_t>(data[start_byte + 0]) << 0U;
      raw_val |= static_cast<uint64_t>(data[start_byte + 1]) << 8U;
      
      yaw = raw_val;
    }
  }

  /**
   * @brief   Create a JSON object for imu_data using the storage
   */
  nlohmann::json to_json() const {
    return {
      {"g_force", g_force},
      {"roll", roll},
      {"pitch", pitch},
      {"yaw", yaw}
    };
  }

  /**
   * @brief   Get the message name: imu_data
   * @return  Returns the message name
   */
  std::string get_message_name() const {
    return "imu_data";
  }
};

/**
 * @brief   Main CAN message Handler
 * @details This function shall dynamically allocate a struct based on the CAN ID
 *          This function shall decode the data, then update the CAN Cache 'm_canInfo' with JSON data
 * @param   id Can message ID
 * @param   data Pointer to the CAN message data
 */
void CanListener::canMessageHandler(uint32_t id, const uint8_t* data) {
  switch (id) {
    case SYSTEM_CAN_MESSAGE_CAN_COMMUNICATION_FAST_ONE_SHOT_MSG: {
      fast_one_shot_msg *message = new fast_one_shot_msg();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_CAN_COMMUNICATION_MEDIUM_ONE_SHOT_MSG: {
      medium_one_shot_msg *message = new medium_one_shot_msg();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_CAN_COMMUNICATION_SLOW_ONE_SHOT_MSG: {
      slow_one_shot_msg *message = new slow_one_shot_msg();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_FRONT_CONTROLLER_DRIVE_STATUS: {
      drive_status *message = new drive_status();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_FRONT_CONTROLLER_MOTOR_STATS_A: {
      motor_stats_a *message = new motor_stats_a();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_FRONT_CONTROLLER_MOTOR_STATS_B: {
      motor_stats_b *message = new motor_stats_b();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_FRONT_CONTROLLER_FC_POWER_GROUP_A: {
      fc_power_group_a *message = new fc_power_group_a();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_FRONT_CONTROLLER_FC_POWER_GROUP_B: {
      fc_power_group_b *message = new fc_power_group_b();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_FRONT_CONTROLLER_FC_POWER_LIGHTS_GROUP: {
      fc_power_lights_group *message = new fc_power_lights_group();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_IMU_GYRO_DATA: {
      gyro_data *message = new gyro_data();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_IMU_ACCEL_DATA: {
      accel_data *message = new accel_data();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_REAR_CONTROLLER_STATUS: {
      rear_controller_status *message = new rear_controller_status();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_BATTERY_STATS_A: {
      battery_stats_a *message = new battery_stats_a();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_BATTERY_STATS_B: {
      battery_stats_b *message = new battery_stats_b();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_POWER_INPUT_STATS: {
      power_input_stats *message = new power_input_stats();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_AFE1_STATUS_A: {
      afe1_status_a *message = new afe1_status_a();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_AFE1_STATUS_B: {
      afe1_status_b *message = new afe1_status_b();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_AFE2_STATUS_A: {
      afe2_status_a *message = new afe2_status_a();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_AFE2_STATUS_B: {
      afe2_status_b *message = new afe2_status_b();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_REAR_CONTROLLER_AFE_TEMPERATURE: {
      afe_temperature *message = new afe_temperature();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_STEERING_STEERING: {
      steering *message = new steering();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    case SYSTEM_CAN_MESSAGE_TELEMETRY_IMU_DATA: {
      imu_data *message = new imu_data();
      message->decode(data);
      m_canInfo[message->get_message_name()] = message->to_json();
      break;
    }
    default: {
      std::cout << "Unknown message ID: " << static_cast<int>(id) << std::endl;
    }
  }
}
