/************************************************************************************************
 * @file   main.c
 *
 * @brief  Main file for bootloader
 *
 * @date   2025-01-08
 * @author Midnight Sun Team #24 - MSXVI
 ************************************************************************************************/

/* Standard library Headers */
#include <stdio.h>
#include <stdbool.h>

/* Inter-component Headers */
#include "flash.h" //..?
#include "core_cm4.h" //..?
#include "system_stm32l4xx.h" //..?

/* Intra-component Headers */
#include "bootloader.h"
#include "bootloader_can.h"
#include "bootloader_can_datagram.h"
//#include "bootloader_can_board_ids.h" autogenerated...?


#define BOOTLOADER_TIMEOUT_MS        15000

volatile uint32_t bootloader_timer = 0;
static uint8_t flash_buffer[BOOTLOADER_PAGE_BYTES];

const Boot_CanSettings can_settings = {
  //.device_id = SYSTEM_CAN_DEVICE_BOOTLOADER autogenerated...?
  .bitrate = BOOT_CAN_BITRATE_500KBPS,
  .loopback = false,
};

void SysTick_Handler(void) {
  bootloader_timer++;
}

Boot_CanMessage msg = { 0 };

int main() {
  /* Set the vector table offset at flash base */
  SCB->VTOR = FLASH_BASE_ADDR;
  boot_can_init(&can_settings);
  bootloader_init();
  if(SysTick_Config(SystemCoreClock / 1000)) {
    send_ack_datagram(0, BOOTLOADER_INTERNAL_ERR);
    while(true); // Hang
  }
  while (true) {
    if (boot_can_receive(&msg) == BOOTLOADER_ERROR_NONE) {
      bootloader_timer = 0;
      bootloader_run(&msg);
    }
    if (bootloader_timer > BOOTLOADER_TIMEOUT_MS) {
        bootloader_timer = 0;
        if (boot_verify_flash_memory() == BOOTLOADER_ERROR_NONE) {
          send_ack_datagram(NACK, BOOTLOADER_TIMEOUT);
          bootloader_jump_app();
        }
        send_ack_datagram(NACK, BOOTLOADER_FLASH_MEMORY_VERIFY_FAILED);
    }
  }
  return 0;
}
