/************************************************************************************************
 * @file   main.c
 *
 * @brief  Main file for bootloader
 *
 * @date   2025-01-08
 * @author Midnight Sun Team #24 - MSXVI
 ************************************************************************************************/

/* Standard library Headers */
#include <stdio.h>
#include <stdbool.h>

/* Inter-component Headers */
#include "bootloader_error.h"
#include "flash.h"
#include "stm32l4xx.h"
#include "system_stm32l4xx.h"
#include "stm32l4xx_hal.h"
#include "core_cm4.h"

void SysTick_Handler(void) {
  HAL_IncTick();
}

/* Intra-component Headers */
#include "bootloader.h"
#include "bootloader_can.h"
#include "bootloader_can_datagram.h"
#include "bootloader_memory_map.h"
//#include "bootloader_can_board_ids.h" autogenerated...?

#define BOOTLOADER_TIMEOUT_MS        15000

static uint8_t flash_buffer[BOOTLOADER_PAGE_BYTES];

const Boot_CanSettings can_settings = {
  //.device_id = SYSTEM_CAN_DEVICE_BOOTLOADER autogenerated...?
  .bitrate = BOOT_CAN_BITRATE_500KBPS,
  .loopback = (BOOTLOADER_LOOPBACK_TESTS_ENABLE == 1),
  .silent = false,
};

Boot_CanMessage msg = { 0 };

int main() {
  __enable_irq();

  /* Set the vector table offset at flash base */
  SCB->VTOR = BOOTLOADER_START_ADDRESS;

  //? Should we just jump app instead
  if (HAL_Init() != 0)
    while (true);

  if (boot_can_init(&can_settings) != BOOTLOADER_ERROR_NONE)
    while(true);

  if (bootloader_init() != BOOTLOADER_ERROR_NONE)
    while(true);

#if BOOTLOADER_LOOPBACK_TESTS_ENABLE == 1
  volatile BootloaderError loopback_test_result = bootloader_loopback_tests(&msg);
  (void)loopback_test_result;
  /* BRKPT for gdb */
  __asm__("nop");
#endif

  uint32_t last_msg_tick = HAL_GetTick();

  while (true) {
    if (boot_can_receive(&msg) == BOOTLOADER_ERROR_NONE) {
      last_msg_tick = HAL_GetTick();
      bootloader_run(&msg);
    }
    if ((HAL_GetTick() - last_msg_tick) > BOOTLOADER_TIMEOUT_MS) {
      last_msg_tick = HAL_GetTick();
      if (boot_verify_flash_memory() == BOOTLOADER_ERROR_NONE) {
        send_ack_datagram(NACK, BOOTLOADER_TIMEOUT);
        bootloader_jump_app();
      }
      send_ack_datagram(NACK, BOOTLOADER_FLASH_MEMORY_VERIFY_FAILED);
    }
  }
  return 0;
}
