/************************************************************************************************
 * @file   pedal_calib_handler.c
 *
 * @brief  Handler for remote pedal calibration via CAN
 *
 * @date   2026-04-27
 * @author Midnight Sun Team #24 - MSXVI
 ************************************************************************************************/

/* Standard library Headers */
#include <stdbool.h>

/* Inter-component Headers */
#include "adc.h"
#include "dac.h"
#include "delay.h"
#include "flash.h"
#include "gpio.h"
#include "log.h"
#include "opamp.h"
#include "pedal_calib.h"
#include "persist.h"
#include "status.h"

/* Intra-component Headers */
#include "front_controller.h"
#include "front_controller_hw_defs.h"
#include "pedal_calib_handler.h"

/**
 * @brief State machine for pedal calibration
 */
typedef struct {
  bool active;
  PedalCalibStatus current_step;
  uint32_t step_start_time_ms;
  PedalCalibrationStorage calib_storage;
  PedalPersistData pedal_persist_data;
  PersistStorage persist_storage;
} PedalCalibrationState;

static PedalCalibrationState s_calib_state = { 0 };

// GPIO addresses for pedal inputs
static const GpioAddress s_accel_pedal_gpio_opamp = { .port = GPIO_PORT_A, .pin = 3 };
static const GpioAddress s_accel_pedal_gpio_raw = { .port = GPIO_PORT_A, .pin = 0 };
static const GpioAddress s_brake_pedal_gpio = { .port = GPIO_PORT_A, .pin = 5 };

// Hardware configuration
#define LAST_PAGE (NUM_FLASH_PAGES - 1)
#define PEDAL_CALIB_DAC_CHANNEL DAC_CHANNEL1
#define PEDAL_CALIB_OPAMP OPAMP_1
#define DELAY_BEFORE_SAMPLING_MS 1000U

/**
 * @brief   Send calibration status via CAN to steering
 */
static StatusCode s_send_calib_status(PedalCalibStatus status) {
  // The auto-generated function will be: set_front_controller_pedal_calib_status_status()
  // This needs to be generated by cantools from the YAML, so for now we use LOG_DEBUG
  LOG_DEBUG("Pedal Calib Status: %u\r\n", status);
  return STATUS_CODE_OK;
}

/**
 * @brief   Initialize calibration hardware
 */
static StatusCode s_init_calib_hardware(void) {
  // Add ADC channels
  adc_add_channel(&s_accel_pedal_gpio_raw);
  adc_add_channel(&s_accel_pedal_gpio_opamp);
  adc_add_channel(&s_brake_pedal_gpio);

  // Initialize hardware
  adc_init();
  opamp_init();
  dac_init();

  // Initialize flash and persist storage
  flash_init();
  StatusCode status = flash_erase(LAST_PAGE, 1U);
  if (status != STATUS_CODE_OK) {
    LOG_DEBUG("flash_erase() failed with status %u\r\n", status);
    return status;
  }

  status = persist_init(&s_calib_state.persist_storage, LAST_PAGE, &s_calib_state.pedal_persist_data,
                        sizeof(s_calib_state.pedal_persist_data), true);
  if (status != STATUS_CODE_OK) {
    LOG_DEBUG("persist_init() failed with status %u\r\n", status);
    return status;
  }

  return STATUS_CODE_OK;
}

/**
 * @brief   Execute one step of the calibration
 */
static StatusCode s_execute_calib_step(void) {
  uint32_t elapsed_time = delay_ms(0);  // Get current time

  switch (s_calib_state.current_step) {
    case PEDAL_CALIB_STATUS_IDLE:
      s_init_calib_hardware();
      s_calib_state.current_step = PEDAL_CALIB_STATUS_ACCEL_RAW_UNPRESSED;
      s_calib_state.step_start_time_ms = delay_ms(0);
      s_send_calib_status(PEDAL_CALIB_STATUS_ACCEL_RAW_UNPRESSED);
      break;

    case PEDAL_CALIB_STATUS_ACCEL_RAW_UNPRESSED:
      if (delay_ms(0) - s_calib_state.step_start_time_ms >= DELAY_BEFORE_SAMPLING_MS) {
        LOG_DEBUG("Sampling accel pedal raw (unpressed)\r\n");
        pedal_calib_sample(&s_calib_state.calib_storage, &s_calib_state.pedal_persist_data.accel_pedal_data_raw,
                          PEDAL_UNPRESSED, (GpioAddress *)&s_accel_pedal_gpio_raw);
        s_calib_state.current_step = PEDAL_CALIB_STATUS_ACCEL_RAW_PRESSED;
        s_calib_state.step_start_time_ms = delay_ms(0);
        s_send_calib_status(PEDAL_CALIB_STATUS_ACCEL_RAW_PRESSED);
      }
      break;

    case PEDAL_CALIB_STATUS_ACCEL_RAW_PRESSED:
      if (delay_ms(0) - s_calib_state.step_start_time_ms >= DELAY_BEFORE_SAMPLING_MS) {
        LOG_DEBUG("Sampling accel pedal raw (pressed)\r\n");
        pedal_calib_sample(&s_calib_state.calib_storage, &s_calib_state.pedal_persist_data.accel_pedal_data_raw,
                          PEDAL_PRESSED, (GpioAddress *)&s_accel_pedal_gpio_raw);

        // Setup OPAMP for next phase
        uint16_t min_raw_reading = (s_calib_state.pedal_persist_data.accel_pedal_data_raw.lower_value <
                                    s_calib_state.pedal_persist_data.accel_pedal_data_raw.upper_value)
                                       ? s_calib_state.pedal_persist_data.accel_pedal_data_raw.lower_value
                                       : s_calib_state.pedal_persist_data.accel_pedal_data_raw.upper_value;

        LOG_DEBUG("Setting MIN raw reading: %u\r\n", min_raw_reading);

        dac_enable_channel(PEDAL_CALIB_DAC_CHANNEL);
        dac_set_voltage(PEDAL_CALIB_DAC_CHANNEL, min_raw_reading);

        OpampConfig config = {
          .vinp_sel = OPAMP_NONINVERTING_IO0,
          .vinm_sel = OPAMP_INVERTING_IO0,
          .output_to_adc = true
        };

        opamp_configure(PEDAL_CALIB_OPAMP, &config);
        opamp_start(PEDAL_CALIB_OPAMP);

        s_calib_state.current_step = PEDAL_CALIB_STATUS_ACCEL_AMP_UNPRESSED;
        s_calib_state.step_start_time_ms = delay_ms(0);
        s_send_calib_status(PEDAL_CALIB_STATUS_ACCEL_AMP_UNPRESSED);
      }
      break;

    case PEDAL_CALIB_STATUS_ACCEL_AMP_UNPRESSED:
      if (delay_ms(0) - s_calib_state.step_start_time_ms >= DELAY_BEFORE_SAMPLING_MS) {
        LOG_DEBUG("Sampling accel pedal amplified (unpressed)\r\n");
        pedal_calib_sample(&s_calib_state.calib_storage, &s_calib_state.pedal_persist_data.accel_pedal_data_amplified,
                          PEDAL_UNPRESSED, (GpioAddress *)&s_accel_pedal_gpio_opamp);
        s_calib_state.current_step = PEDAL_CALIB_STATUS_ACCEL_AMP_PRESSED;
        s_calib_state.step_start_time_ms = delay_ms(0);
        s_send_calib_status(PEDAL_CALIB_STATUS_ACCEL_AMP_PRESSED);
      }
      break;

    case PEDAL_CALIB_STATUS_ACCEL_AMP_PRESSED:
      if (delay_ms(0) - s_calib_state.step_start_time_ms >= DELAY_BEFORE_SAMPLING_MS) {
        LOG_DEBUG("Sampling accel pedal amplified (pressed)\r\n");
        pedal_calib_sample(&s_calib_state.calib_storage, &s_calib_state.pedal_persist_data.accel_pedal_data_amplified,
                          PEDAL_PRESSED, (GpioAddress *)&s_accel_pedal_gpio_opamp);
        s_calib_state.current_step = PEDAL_CALIB_STATUS_BRAKE_UNPRESSED;
        s_calib_state.step_start_time_ms = delay_ms(0);
        s_send_calib_status(PEDAL_CALIB_STATUS_BRAKE_UNPRESSED);
      }
      break;

    case PEDAL_CALIB_STATUS_BRAKE_UNPRESSED:
      if (delay_ms(0) - s_calib_state.step_start_time_ms >= DELAY_BEFORE_SAMPLING_MS) {
        LOG_DEBUG("Sampling brake pedal (unpressed)\r\n");
        pedal_calib_sample(&s_calib_state.calib_storage, &s_calib_state.pedal_persist_data.brake_pedal_data,
                          PEDAL_UNPRESSED, (GpioAddress *)&s_brake_pedal_gpio);
        s_calib_state.current_step = PEDAL_CALIB_STATUS_BRAKE_PRESSED;
        s_calib_state.step_start_time_ms = delay_ms(0);
        s_send_calib_status(PEDAL_CALIB_STATUS_BRAKE_PRESSED);
      }
      break;

    case PEDAL_CALIB_STATUS_BRAKE_PRESSED:
      if (delay_ms(0) - s_calib_state.step_start_time_ms >= DELAY_BEFORE_SAMPLING_MS) {
        LOG_DEBUG("Sampling brake pedal (pressed)\r\n");
        pedal_calib_sample(&s_calib_state.calib_storage, &s_calib_state.pedal_persist_data.brake_pedal_data,
                          PEDAL_PRESSED, (GpioAddress *)&s_brake_pedal_gpio);

        // Commit to persist storage
        StatusCode status = persist_commit(&s_calib_state.persist_storage);
        if (status != STATUS_CODE_OK) {
          LOG_DEBUG("persist_commit() failed with status %u\r\n", status);
          s_calib_state.current_step = PEDAL_CALIB_STATUS_ERROR;
          s_send_calib_status(PEDAL_CALIB_STATUS_ERROR);
        } else {
          LOG_DEBUG("Pedal calibration complete!\r\n");
          s_calib_state.current_step = PEDAL_CALIB_STATUS_COMPLETE;
          s_send_calib_status(PEDAL_CALIB_STATUS_COMPLETE);
        }
      }
      break;

    case PEDAL_CALIB_STATUS_COMPLETE:
    case PEDAL_CALIB_STATUS_ERROR:
      // Calibration is done, will be reset by next init
      break;

    default:
      return STATUS_CODE_INVALID_STATE;
  }

  return STATUS_CODE_OK;
}

StatusCode pedal_calib_handler_init(FrontControllerStorage *storage) {
  if (storage == NULL) {
    return STATUS_CODE_INVALID_ARGS;
  }

  s_calib_state.active = false;
  s_calib_state.current_step = PEDAL_CALIB_STATUS_IDLE;
  s_calib_state.calib_storage = (PedalCalibrationStorage){ 0 };
  s_calib_state.pedal_persist_data = (PedalPersistData){ 0 };

  return STATUS_CODE_OK;
}

StatusCode pedal_calib_handler_rx(FrontControllerStorage *storage) {
  if (storage == NULL) {
    return STATUS_CODE_INVALID_ARGS;
  }

  // Check if there's a calibration request from steering
  // The auto-generated function will be: get_steering_pedal_calib_request_command()
  // For now, we just check a flag that would be set by the CAN handler
  // This will be completed when the auto-generated code is available

  if (!s_calib_state.active) {
    // Check for calibration start request (would be from CAN message)
    // s_calib_state.active = get_steering_pedal_calib_request_command() > 0;
  }

  return STATUS_CODE_OK;
}

StatusCode pedal_calib_handler_run(FrontControllerStorage *storage) {
  if (storage == NULL) {
    return STATUS_CODE_INVALID_ARGS;
  }

  if (!s_calib_state.active) {
    return STATUS_CODE_OK;
  }

  return s_execute_calib_step();
}
