name: Deploy Doxygen Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake graphviz

      - name: Build and Install Doxygen 1.9.5
        run: |
          wget https://github.com/doxygen/doxygen/archive/Release_1_9_5.tar.gz
          tar -xzf Release_1_9_5.tar.gz
          cd doxygen-Release_1_9_5
          mkdir build
          cd build
          cmake -G "Unix Makefiles" ..
          make
          sudo make install

      - name: Generate Doxygen Documentation
        run: |
          doxygen --version
          doxygen doxygen/Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doxygen/html
          publish_branch: doxygen-pages
          force_orphan: true
          full_commit_message: 'Doxygen: update documentation'